### ISSUE TITLE
Reply Box and Comment issues by a user

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1098]
I see there is one issue still persist in my phone post new update . While replying to any comment, the reply box is showing the previous written comment ....mean the last comment I made
Below two screenshot, I was making reply to erikah comment,
![](https://cdn.discordapp.com/attachments/385448634197737484/615931622273056799/Screenshot_20190827-210119.png)

But on clicking the reply button I am getting the last comment I made on taskmaster post.
![](https://cdn.discordapp.com/attachments/385448634197737484/615931792217735180/Screenshot_20190827-210132.png)

I think the message box needs to be blanked all the time 
> after successful submitting the last message

# 2
Another one, there seems toe certain limitation on the reply tab. However thb "Pencil" right at the middle is not allowing to click the "reply" button...refer below screenshot for example.
![](https://cdn.discordapp.com/attachments/385448634197737484/615933511035256853/Screenshot_20190827-210815.png)

**Comment by feruzm** [comment]
First issue, are you sure you are using latest version/update? Please check PlayStore @horpeyloaded we have pushed update yesterday and it already had fix I think.
@mistikk and @ue please take a look at 2nd issue, also double check 1st one please. Thanks

**Comment by mistikk** [comment]
In the first issue; if you wrote a comment but if you didnt send that, esteem saves to this comment and i guess you saw that. If you send that, it will remove from esteem drafts and you will not see any more, can you check with this rule @horpeyloaded

**Comment by horpeyloaded** [comment]
Great, I understand how it works. I just updated my app again, I will verify now, thanks.
