### ISSUE TITLE
Parent post action for replies tab

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1099]
When you are mentioned in a comment and you click the notification, it only shows the comment you were mentioned in, Could it be possible to add the whole post and then show where you were mentioned?

### It's necessary, please implement

**Comment by feruzm** [comment]
I thought we already had this, @mistikk and @ue please check

**Comment by horpeyloaded** [comment]
This is the reply TAB, no way/button available to go to the primary content.
![](https://i.imgur.com/6hMyKDZ.png)

**Comment by horpeyloaded** [comment]
I clicked the reply from the notification Tab, I can't go-to the parent post as well.
![](https://i.imgur.com/3HFr6YA.png)

**Comment by mistikk** [comment]
@horpeyloaded fixed

**Comment by horpeyloaded** [comment]
Thanks.
@mistikk It’s enabled for notification replies but no yet in the **Replies tab**. 

What if I wanted to go to the parent post in which I got a reply after few days, this wouldn't be possible from the reply tab, I will have to search out the post manually which will take time or piss users off.

**Comment by horpeyloaded** [comment]
Ex: I wanted to go to the parent post of this reply but not possible and I wanted to be sure of the post which the user commented on. 
![](https://i.imgur.com/7BCJP7q.png)

There should be a box pointing  the parent post or comment @mistikk

**Comment by horpeyloaded** [comment]
Ex: I wanted to go to the parent post of this reply but not possible and I wanted to be sure of the post which the user commented on. 
![](https://i.imgur.com/7BCJP7q.png)

There should be a box pointing  the parent post or comment @mistikk

**Comment by mistikk** [comment]
okay it is not implemented, right. I will reopen and will edit to title for reply tab

**Comment by mistikk** [comment]
it is implemented, we put a new option as `open thread` to long press action @horpeyloaded

**Comment by horpeyloaded** [comment]
Not implemented to my Taste. You can check out Busy to see how it works. I have explained up but can't find any chances yet.

**Comment by horpeyloaded** [comment]
I can't go back to the parent thread of replies. Check replies tab, you will find out what I mean.

**Comment by feruzm** [comment]
@horpeyloaded you can go to one parent for now.

@mistikk you can easily improve feature to allow opening all parents one by one

**Comment by mistikk** [comment]
fixed
