### ISSUE TITLE
Feature: Open Steem link through the search bar

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1103]
Users should be able to open any Steemit link by pasting it into the search bar (steemit, busy, steempeak should be supported) rather than clicking on link to pop-up app.

**Comment by mistikk** [comment]
It is already implemented for posts, also yesterday we added for comments @horpeyloaded. I am closing issue, can you check to this feature, if it doesnt work you can reopen to issue

**Comment by horpeyloaded** [comment]
@mistikk, it doesn't work

**Comment by mistikk** [comment]
can you record to issue @horpeyloaded

**Comment by mistikk** [comment]
Ooh okay, I am sorry i was understand as browser search, okay i am reopening

**Comment by horpeyloaded** [comment]
No p, thanks for the good work ✌
