### ISSUE TITLE
Missing Posting Authority Key Error

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1108]
On the first login attempt, user is asked to specify PIN and user set PIN which is good. 

Now the issue, if the user disables PIN option from settings, then the user will get this error `Missing Posting Authority Key Error` when the user 👥 tries to perform activities like upvote, comment with the app, the solution only is for user to logout and login again with the PIN disabled. And vise-versa if the PIN is also disable and user enable it back the error with key will pop up again.

**Please fix this ASAP** login in and out is a pain in the ass for multiple account users 😉. 

![](https://i.imgur.com/fXlc8Mu.png)

**Comment by mistikk** [comment]
fixed
