### ISSUE TITLE
Update immediately

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1139]
Indicate on post instantly when a user votes, comment… 

Presently it doesn't until user 👥 refresh

**Comment by mistikk** [comment]
Can we implement to this, i am not sure @feruzm. Maybe we can refresh as automatically every 10 sec. but i think user will not want to that, because it will use to internet data as unnecessary sometimes

**Comment by feruzm** [comment]
@horpeyloaded when you vote or comment, it does update but if you are talking about when other users votes or comments, this needs to be carefully done to not cause extra bandwidth usage.
If you are talking about feed update should be automatic, it can be updated manually by pull down to refresh or when app restarts
