### ISSUE TITLE
Time missing on vote lists 

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1141]
-

**Comment by mistikk** [comment]
can you share screenshot @horpeyloaded

**Comment by mistikk** [comment]
are you still seeing this issue @horpeyloaded

**Comment by horpeyloaded** [comment]
![](https://cdn.steemitimages.com/DQmQ5TLeXT8RRwS1PEtAAGLBWpWYXARKGxdzvAVMyZavftF/Screenshot_2019-10-17-12-26-14.png)

**Comment by mistikk** [comment]
fixed #1240
