### ISSUE TITLE
Navigation Button for Amdroid

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1143]
For the latest app, the navigation button background color is white instead of black.

![](https://cdn.discordapp.com/attachments/417386914983968769/618985874700369920/Screenshot_2019-09-05-02-46-46.png)

**Comment by horpeyloaded** [comment]
I can't see my navigate button 🔘. Instead make the buttons Black with white background

**Comment by mistikk** [comment]
Fixed
