### ISSUE TITLE
Editor page refactoring

### ISSUE THREAD

**Issue by mistikk** [esteemapp/esteem-mobile#1161]
- [x] Split container and screen
- [x] Android selection issues
- [x] #1144 
- [x] #820

**Comment by ue** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/b3087696-38a6-443b-8645-2f388163df81-7b1c293c-8ae2-4729-a9ee-f35e99cf1007-v1.png?transparent=1&palette=1&width=246)
