### ISSUE TITLE
Abit and other comments shows up first when vising users’ comments

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1164]
Users automatically see @abit's…  comments when they try to click their or other users’ comments

`Showing comments of 3 years ago that are not related to the user`

**Comment by horpeyloaded** [comment]
<img src="https://i.ibb.co/7ScXJX8/Screenshot-2019-09-19-23-27-25.png" alt="Screenshot-2019-09-19-23-27-25" border="0">

**Comment by mistikk** [comment]
fixed
