### ISSUE TITLE
Still getting push notifications after it has been disabled

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1165]
Notifications are coming in like they were not disabled

**Comment by mistikk** [comment]
@horpeyloaded can you check last version(v2.2.3)

**Comment by horpeyloaded** [comment]
I'm using the lastest version

**Comment by mistikk** [comment]
can you share screenshot of setting page @horpeyloaded

**Comment by horpeyloaded** [comment]
I still get push notifications while it's turned off in settings. 

I see you pull a fix.

**Comment by mistikk** [comment]
yes i found the issue, fixed

**Comment by horpeyloaded** [comment]
Great 👍

**Comment by ue** [comment]
Fixed
