### ISSUE TITLE
Suggestion on SAVE Button by Bala

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1182]
Hello team, I would like to suggest moving the save button to somewhere else instead of having it near the back button. I have had problems on the past where I hit the back button instead of save button trying to save my article. If I do that all my efforts in writing the article would be lost and it will be so frustrating. This has happened to me a couple of times in the past. 

When I draft article in my mobile, I keep saving the article frequently using that option so it is risky to have that near back button. Also imagine this for someone with a fat finger.

![](https://cdn.discordapp.com/attachments/445901975301914624/626307797037875201/Screenshot_20190925-120901.png)

One suggestion could be to move the save button to the place where schedule button is there and schedule button next to back button. Because, I'm sure people will try to schedule only after they complete the article and that shouldn't be a frequently used button.

**Comment by ue** [comment]
fixed
