### ISSUE TITLE
date and time error

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#1195]
users are still getting this error somehow we need to see if we can have plugin to auto fix that for user

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@good-karma` in `#📲-esteem-mobile`.

**Comment by mistikk** [comment]
I couldn't find any example or solution about that. I guess devices not allow to change this time. Maybe we can add more information to alert message like `your time is ...., but current time is ...`. User can see difference @feruzm

**Comment by feruzm** [comment]
Yes we can try that. Meanwhile I will check if there is better way
