### ISSUE TITLE
2.2.2 click active crash

### ISSUE THREAD

**Issue by blackfireburn** [esteemapp/esteem-mobile#1202]
Hello, I couldn't see this in the list.
Android 9 oxygen os 
August security patch
Oneplus 6t
Esteem 2.2.2
Popular page crash when selecting active
to recreate
  When opening the app go to popular let trending load
In drop down select active.
It does not load
Select another type such as trending. This now also fails to load.
Select a different section such as hot, then go to active. Same behaviour crash and then all other popular pages fail to load.
Feed still loads correctly and so does profile.
Resolved by restarting app
Let me know if there is anything you want me to try.

**Comment by feruzm** [comment]
This depends on what server you are connecting. Try selecting rpc.esteem.app server from Settings page. api.steemit.com server doesn't support those filters.

**Comment by blackfireburn** [comment]
Thats done it. I didn't change the default server from when I installed the app. Should RPC be the default?
