### ISSUE TITLE
Critical bug

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#1248]
Make sure if sponsored fail to respond from backend, steem posts should still work. All backend dependencies should be handled such that they don't block functionality of app increase they return error or fail to respond, gracefully show alert or error message to user without alarming them too much

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@good-karma` in `#📲-esteem-mobile`.

**Comment by ue** [comment]
@feruzm Fixed.
