### ISSUE TITLE
Add filters on tag explorer

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#1260]
This page should have Trending, Hot, Created filters, Let's add it, current screen only showing `https://esteem.app/trending/esteem`, other filters are must, `Trending, Hot, Created`.
 ![](https://cdn.discordapp.com/attachments/464486139756281856/641122081341308929/Simulator_Screen_Shot_-_iPhone_6s_-_2019-11-05_at_05.49.41.png)

---
Beep, boop, I'm [a bot](https://github.com/LeagueSandbox/IssueBot)! This issue was created by `@good-karma` in `#📲-esteem-mobile`.

**Comment by ue** [comment]
Fixed
