### ISSUE TITLE
UI/UX improvement

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1307]
Please I would love the UI/UX of eSteem mobile app to be more streamlined with devices. Download latest Gmail app from PlayStore to see what I'm talking about. I have seen couple of apps using that model/material design and their products are great. This is also the reason people still prefers Partiko's interface to eSteem.  

PS: It’s like an environment of app where users don't know they are switching from one part of the app to another and in a reality they are doing it.

@feruzm

**Comment by feruzm** [comment]
@horpeyloaded thanks, please do share some screenshots here or on discord to get better idea, because gmail might have slightly different views on different devices.

**Comment by horpeyloaded** [comment]
Waiting for the next release to see what has been improved in eSteem UX/UI. I can't seem to send screenshot of the app UI I'm talking about. 

I can only explain, what I notice is that, if a user opens Android App I enjoyed using and Partiko, it will seem as if they were still hovering their phone literally without opened app, user won't feel the effect of app they just opened on their phone, let me just say app flexibility.

**Comment by feruzm** [comment]
Right now, each page being revisited and improved in 2.2.3, if changes are bigger and requires substantial changes it is moved to next major update. What we are doing right now, having dedicated wallet for tokens, more obvious access points, getting rid of some dropdowns, etc. etc.
