### ISSUE TITLE
Payout Improvement

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#1354]
The present payout of eSteem looks absurd
![Screenshot_2019-12-04-15-02-45.png](https://cdn.steemitimages.com/DQmQGWwGdD2LkKtY7ZhvYpMvqVyp33HQRHcqKrB6nEWngx7/Screenshot_2019-12-04-15-02-45.png)

Please change it to how Steemit.com displays payout. 
![Screenshot_2019-12-04-15-01-31.png](https://cdn.steemitimages.com/DQmNt7SUd4Z84gLbt65VTmfU52frXe1Gc1pNGCEzbkEJUnP/Screenshot_2019-12-04-15-01-31.png)

**Comment by feruzm** [comment]
👍

**Comment by feruzm** [comment]
added into upcoming release ![Simulator Screen Shot - iPhone X - 2019-12-10 at 13 20 06](https://user-images.githubusercontent.com/3015990/70525363-d8affd00-1b4f-11ea-817c-48145dfcec67.png)
