### ISSUE TITLE
Android back softkey button closes app

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-mobile#189]
Should work as `back` navigation instead...

**Comment by fildunsky** [comment]
Work of Back button in Android should be modified a little bit so it should be user friendly acting similarly as in any other app. Say when user don't have any actions done yet Back button should open Android Homescreen (Launcher) and if we are reading the post back button should get us back to the feed etc...

**Comment by ue** [comment]
revelant #451
