### ISSUE TITLE
Sending feedback feature

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#242]
We should have feature where user can send feedback/suggestions/bugs/etc. from inside app quickly.

**Comment by mistikk** [comment]
We can use github api for that https://developer.github.com/v3/issues/#create-an-issue

**Comment by mistikk** [comment]
@fildunsky do you have any design suggestion about that feature?

**Comment by feruzm** [comment]
Do user require github credentials for this or they can just submit issue without login, @mistikk ?

**Comment by mistikk** [comment]
Do we have any design for that @fildunsky ?

**Comment by fildunsky** [comment]
Is it really worth it spending time on design and coding that feature rather than just redirect to default email client with predefined email address, subject and some template email having few fileds inside email body like: steps to reproduce bug etc?

**Comment by feruzm** [comment]
Yes, it can be predefined email content actually.

Subject: Feedback/Bug report
Content: 

What user writes or describes the issue and then.

Application automatically fills in:
App version, Build number
Platform type (iOS, Android)
Device type or OS version

@mistikk in this case, it is much easier to handle.

**Comment by ue** [comment]
@feruzm Done.

**Comment by feruzm** [comment]
Well, done... let's schedule this into next release 👍
