### ISSUE TITLE
Profile page comments/replies

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#257]
When user opens their own profile show replies as 2nd tab, but when user opens other peoples account show them comments as 2nd tab. This way, if you checking someone’s profile you can read their comments, but if you are checking your own profile you want to check replies.

@fildunsky, @ue, @mistikk

**Comment by ue** [comment]
@feruzm Done.

**Comment by feruzm** [comment]
Nice 👏 👍
