### ISSUE TITLE
Post render pull-left, right 

### ISSUE THREAD

**Issue by ue** [esteemapp/esteem-mobile#275]

**Comment by horpeyloaded** [comment]
### FLOAT LEFT
<div class="pull-left">
contents here
</div>

### FLOAT RIGHT
<div class="pull-right"> 
contents here
</div>

### CENTRALIZE
<center><p>contents</p></center>

### JUSTIFY YOUR ARTICLE
<div class="text-justify">
contents here
</div> 

### RED COLOUR TETX
<div class="phishy"> contents here </div>

**Comment by horpeyloaded** [comment]
@ue and @feruzm please don't forget this as well; it's related to post preview rendering. I see that @ue has fixed `<center>` tag rendering.

**Comment by ue** [comment]
can test using this post after new release https://steemit.com/table/@demo/jhj
