### ISSUE TITLE
code tag doesnt show correctly for some devices

### ISSUE THREAD

**Issue by ue** [esteemapp/esteem-mobile#313]

**Comment by horpeyloaded** [comment]
##### Tags Error
Tags Edit Preview
![](https://i.ibb.co/rb4Gd9X/Screenshot-2019-01-05-22-37-58.png)

**Deleted All Tags Preview**
![](https://i.ibb.co/3f283Sv/Screenshot-2019-01-05-22-36-34.png)

**Manual Input tags after I deleted all preview** 
![](https://i.ibb.co/X2CNN2x/Screenshot-2019-01-05-22-37-03.png)
