### ISSUE TITLE
Issues and Suggestions

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#323]

**Comment by ue** [comment]
4 fixed
1 fixed
2 fixed

**Comment by mistikk** [comment]
I moved all bugs to new issues for easy tracking

**Comment by horpeyloaded** [comment]
Good @mistikk. Now, I will open new issue for each bug for easy tracking and keep this for suggestions.

**Comment by horpeyloaded** [comment]
Please, these indicators are too small, sometimes I tap it like 5 times for it to be responsive.
![](https://i.ibb.co/3z3pp3z/Screenshot-2019-01-05-22-40-49.png)

![](https://i.ibb.co/94kVkQY/Screenshot-2019-01-05-22-40-17.png)

Collapse is need for comments like the below pix
![](https://i.ibb.co/42SYqPR/Screenshot-2019-01-05-22-46-36.png)

**Comment by horpeyloaded** [comment]
Tags Error
Tags Edit Preview
![](https://i.ibb.co/rb4Gd9X/Screenshot-2019-01-05-22-37-58.png)

Deleted 
![](https://i.ibb.co/X2CNN2x/Screenshot-2019-01-05-22-37-03.png)

Deleted Tag Preview
![](https://i.ibb.co/3f283Sv/Screenshot-2019-01-05-22-36-34.png)

**Comment by horpeyloaded** [comment]
##### Indicate Low Ratings Posts and Comments
![](https://i.ibb.co/3pXG2S1/Screenshot-2019-01-05-12-00-40.png)

![](https://i.ibb.co/P5rwtRW/Screenshot-2019-01-05-12-00-30.png)

![](https://i.ibb.co/x2mYJpd/Screenshot-2019-01-05-11-59-36.png)

**Comment by horpeyloaded** [comment]
#### Collapse is needed for comments like the below pix
![](https://i.ibb.co/42SYqPR/Screenshot-2019-01-05-22-46-36.png)

**Comment by feruzm** [comment]
@horpeyloaded Please feel free to create separate issues, rather than adding everything in one issue. Separate issue helps to prioritize and track progress of each bug/suggestion/feature. Thanks!

**Comment by horpeyloaded** [comment]
Okay boss, I will do that for this issue and for subsequent issue/suggestion/feature.
