### ISSUE TITLE
Profile details misaligned design

### ISSUE THREAD

**Issue by mistikk** [esteemapp/esteem-mobile#327]
Check @adsactly profile; check the about (location, website) it looks odd, misaligned. and Check ✔ @flysky account as well, it looks scary

![](https://cdn.discordapp.com/attachments/428544657698455554/530324114901303296/Screenshot_2019-01-03-10-56-55.png)

**Comment by horpeyloaded** [comment]
Not fixed

**Comment by ue** [comment]
@horpeyloaded can you share screenshot

**Comment by horpeyloaded** [comment]
<img src="https://i.ibb.co/Mpr67Sj/Screenshot-2019-01-11-23-32-33.png" alt="Screenshot-2019-01-11-23-32-33" border="0">
<img src="https://i.ibb.co/Bcs7WPv/Screenshot-2019-01-11-23-31-36.png" alt="Screenshot-2019-01-11-23-31-36" border="0">

**Comment by horpeyloaded** [comment]
@ue ^^

**Comment by ue** [comment]
Could you please compare first screenshots and last one also you can draw a line behind the icons. If you talking about the icons I understand these. Them already fixed

**Comment by ue** [comment]
https://img.esteem.ws/ak4s8t8d7c.jpg

**Comment by horpeyloaded** [comment]
The text should be horizontal instead of vertical.
See this;
<img src="https://i.ibb.co/KVHzyGP/Screenshot-2019-01-12-00-01-06.png" alt="Screenshot-2019-01-12-00-01-06" border="0">

**Comment by ue** [comment]
Nope, here is working as expected. If these line not fit for width it will turn to horizontal but if fit for the line it will be vertical. So its working as design

**Comment by horpeyloaded** [comment]
@ue can we make those texts centralized instead of left align @fildunsky?

**Comment by fildunsky** [comment]
Yes, that could be better

**Comment by ue** [comment]
What is mean of centeralize? @fildunsky @horpeyloaded

**Comment by fildunsky** [comment]
alignment of whole row with profile details by center similar like `<center>` tag does in html

**Comment by ue** [comment]
so this line should be vertical? or should I keep them like this? Also if you guys talking about last picture centralize already center for both side.
