### ISSUE TITLE
RC Full time missing when you visit your own profile

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#351]
Logged in profile
![](https://i.ibb.co/KwThJ1Y/Screenshot-2019-01-05-11-45-34.png)

User's Profile
![](https://i.ibb.co/gJRQ3gn/Screenshot-2019-01-05-11-42-02.png)

**Comment by ue** [comment]
it is already full(100%) thats why its missing.

**Comment by horpeyloaded** [comment]
oooh! Thank you 😆! You may close this box
