### ISSUE TITLE
Suggestion: Pop eSteem mobile as one of the suggested apps if a link to Steem blockchain is clicked

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#369]
steemit, busy, steempeak should all be supported. 
**NB** eSteem should be the first suggested app, please give it the highest priority.
![](https://i.ibb.co/CQJVk23/Screenshot-2019-01-04-07-19-04.png)

Also open eSteem mobile when esteem://link is visited

**Comment by feruzm** [comment]
Deeplinking
https://medium.com/react-native-training/deep-linking-your-react-native-app-d87c39a1ad5e
and whitelisted incoming links, so whenever user clicks on steemit.com and/or busy.org, steempeak.com links on mobile show, them option to open with eSteem.
https://developer.android.com/training/app-links/deep-linking#adding-filters

**Comment by feruzm** [comment]
moved to next iteration because there was some issues on Android devices
