### ISSUE TITLE
Increase the size of multiple account indicator

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#371]
Please, these indicators are too small, sometimes I tap it like 5 times for it to be responsive. Or better make a hidden circle around them so they become easily clickable.
![](https://i.ibb.co/3z3pp3z/Screenshot-2019-01-05-22-40-49.png)

![](https://i.ibb.co/94kVkQY/Screenshot-2019-01-05-22-40-17.png)

**Comment by fildunsky** [comment]
Good point I was trying to fix it as well. Here is solution on Zeplin https://zpl.io/bPmjDXy
I will explain there. It's easy...
