### ISSUE TITLE
push notification icon

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#376]
![](https://i.ibb.co/N6Z3327/Screenshot-2019-01-07-13-20-01.png)

![](https://i.ibb.co/6tmkjCk/Screenshot-2019-01-07-13-21-03.png)

Check this: https://docs.microsoft.com/en-us/appcenter/sdk/push/android#configure-notifications-default-values

**Comment by feruzm** [comment]
@horpeyloaded are you using Google play store version? Do you still see this?

**Comment by horpeyloaded** [comment]
Yes and Yes @feruzm

**Comment by feruzm** [comment]
ok, thanks added to next week's release to check. for testing, could you specify device and OS versions?

**Comment by horpeyloaded** [comment]
Android v8
Infinix note 5

I have friends with this similar issue as well

**Comment by horpeyloaded** [comment]
Not fixed

**Comment by mistikk** [comment]
Did you re install after last release? @horpeyloaded

**Comment by horpeyloaded** [comment]
Yup I did but still not showing app icon.
