### ISSUE TITLE
[BUG] Esteemapp v2 android doesn't show tables created in markdown after post is published.

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#385]
**Describe the bug**
I don't actually know if this is a bug, or how the app was designed to function. But, After creating a table using markdown, when previewing the post, I could see the table. But when the post is published, the table is shown as plain texts. 

**To Reproduce**
1. Go to post editor
2. Click on the plus (+)  sign to create a new post.
3. Create a post containing a table of content. (You can preview to ensure you created a table)
4. Publish the post.
5. Open the post like you want to read it.
6. See error.

**Expected behavior**
I expected that if I could create a table on the app, and it shows when I preview it before publishing, it will be a table even after publishing.

**Screenshots or Video**
![screenshot_2019-01-09-11-32-03-780_app esteem mobile](https://user-images.githubusercontent.com/40593824/50894525-b7a4d080-1403-11e9-82f4-6fb531c57a07.png)

![screenshot_2019-01-09-11-32-10-059_app esteem mobile](https://user-images.githubusercontent.com/40593824/50894538-c25f6580-1403-11e9-9b32-1efd42db38f8.png)

![screenshot_2019-01-09-11-32-23-503_app esteem mobile](https://user-images.githubusercontent.com/40593824/50894551-c8eddd00-1403-11e9-898d-323994878746.png)

**Smartphone:**
 - Device: [Xiaomi Redmi Note 5 pro]
 - OS: [Android]
 - Version [Android 8.1]

**Comment by feruzm** [comment]
Thank you @HarryHeights for reporting... We will look into this
