### ISSUE TITLE
Esteemapp v2 Android.  There is a capture image button beneath the settings page.

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#386]
**Describe the bug**
There is an icon beneath the settings page on the icon. The capture image icon to be precise. Clicking it performs the expected action though. Which is to capture an image.

**To Reproduce**
1. Go to to settings on the app
2. See error

**Expected behavior**

As expected, the settings page should only contain useful options that affect's the app's functionalities. I didn't expect to see an icon there. If this isn't a mistake and the button is actually meant to be there, it is not fitted properly on display. It is actually half cut. 

**Screenshots or Video**

![screenshot_2019-01-09-11-59-38-085_app esteem mobile](https://user-images.githubusercontent.com/40593824/50895412-4fa3b980-1406-11e9-92db-7cf0d5fdd9ba.png)

**Smartphone :**
 - Device: [Xiaomi redmi note 5 pro]
 - OS: [Android]
 - Version [Android 8.1]

**Additional context**
If this is not a bug and the button is deliberately placed there, and the idea is to allow users access the post editor even from the settings page, then (+) icon which signifies post creation should be placed there.

**Comment by feruzm** [comment]
@HarryHeights looks like this is bug with window size. We will test this on similar sized device and apply necessary fixes, thanks!

**Comment by feruzm** [comment]
related, bottom of modal should be fixed, modal size issue.

![](https://cdn.discordapp.com/attachments/487610005558657034/532889561588826122/Screenshot_2019-01-10-13-52-32.png)
