### ISSUE TITLE
Post image covers cut

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-mobile#397]
Image previews on eSteem Mobile v2 are cut now:

![screenshot_20190111-091039_esteem](https://user-images.githubusercontent.com/32987666/51021848-bacec680-1593-11e9-9963-cc5bbc89e031.jpg)

### Surfer
Surfer shows it correctly without cut

<img width="752" alt="2019-01-11 11 24 40" src="https://user-images.githubusercontent.com/32987666/51021843-b86c6c80-1593-11e9-95f8-ca3fc937d03a.png">

Original image for [post ](https://steemit.com/esteem/@dunsky/fresh-illustration-for-esteem) cover:
![](https://steemitimages.com/640x0/https://img.esteem.ws/pealjes08r.png)

### I mean
We should make default cover proportions height bigger

![screenshot_20190111-091039_esteem](https://user-images.githubusercontent.com/32987666/51021953-03867f80-1594-11e9-8ca4-7afd42f96700.jpg)

**Comment by mistikk** [comment]
If we do that, we will see white or black background on left and right of image. It is okay for surfer, but in mobile devices I think it will see strange. I mean user will see different with images, are we sure user want to this? @fildunsky @feruzm

**Comment by feruzm** [comment]
I wouldn't mind seeing image cut a bit due to mobile device sizes, user can always see full image inside post.

**Comment by fildunsky** [comment]
It's okay, no problem but strange a bit... How come that all post images on eSteem Surfer are same size (proportions) and on Steemit as well but on Mobile we are showing different? Is it really impossible to implement without white/black/blank spaces? Even basic HTML code can do that. We are forming some standards here and if we will cut them like that like it is on out mobile app now it means we don't care about that standards.

We can show full image if it is similar proportions like we are using in our posts 1000x600 px and it's okay to cut it if it has bigger height.

**Comment by feruzm** [comment]
I am sure @mistikk and @ue can double check stylesheet again to make sure we using proper styling if not we can always request resize from server with size we want, just change `0x0` to something that fits what @fildunsky is asking...

**Comment by mistikk** [comment]
In surfer, images already cut, just it uses different rate, we can change rate, it is mean we should increase image height, right now it is 200, 220-250 will be okay or we can stretch like ugur already made
![screen shot 2019-01-15 at 17 18 07](https://user-images.githubusercontent.com/8211075/51186754-6e64ed00-18eb-11e9-8e14-64acd356e251.png)

**Comment by fildunsky** [comment]
Yes, let's use same rate as in Surfer. That's what I was trying to tell :)

**Comment by ue** [comment]
we should not change the height these cards already has enough. these are totaly work as design. if its really necessary there is two option one of them we can keep like that other one is can change cover style as stretch then can change url request as 800x0 or something but its also will hard to render. So it not a good option to playing with height.

**Comment by fildunsky** [comment]
We should not distort image propoportions. Please better revert it back to cut if we can not fix it still... Now all images in previews are distorted and looks really weird.

**Comment by ue** [comment]
Fixed
