### ISSUE TITLE
Header avatars small visual tweak

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-mobile#404]
<img width="625" alt="2019-01-11 16 33 05" src="https://user-images.githubusercontent.com/32987666/51036760-27ab8600-15bf-11e9-9157-0b7243c422a9.png">

- [ ] Would be great to have same space in between top, bottom and left/right sides as shown on the screen above.
- [ ] For profiles with avatar on right side (like eSteem on the screenshot) we could also use right text alignment

**Comment by ue** [comment]
Fixed
