### ISSUE TITLE
Profile replies indicator 

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#413]
on my profile replies section, if I have answered any of replies, have indicator that says replied, cc @fildunsky.

**Comment by mistikk** [comment]
We are using dsteem for getting replies, It is not give to this information. If we want to implement this feature, we should make call for every replies, it is mean we will make 10 call just for replies page. What you are thinking about that, should we implement? @feruzm

**Comment by fildunsky** [comment]
We've planned to show it like this https://zpl.io/25wOxE0
Let me know if it is still good for us or should I search for different variations, please...

**Comment by mistikk** [comment]
hmm it was for comments, will we implement for replies @feruzm @fildunsky
