### ISSUE TITLE
eSteem Mobile v2 - User's name is set to @undefined after  making changes via settings

### ISSUE THREAD

**Issue by realrufans** [esteemapp/esteem-mobile#414]
#### Expected behavior

I expect eSteem Mobile v2 to display user's name immediately after making changes via settings page.

#### Actual behavior

It was observed that, User's name is set to ```@undefined``` just after making changes via settings.

#### How to reproduce

* Launch app.
* Locate and click on settings from the navigation button at top left.
* change your language.
* click back button then repeat step 2 and 3.
* Click back button, Locate and click on profile from the navigation button at top left.

#### Bug
![GBWA-20190112191547.jpg](https://cdn.steemitimages.com/DQmPgbb61Z3cA9Ezxzoi9EnhDcPqVaTRrRWiFfzKz8rfB5u/GBWA-20190112191547.jpg)

#### Browser/App version: 
  eSteem Mobile V2 (V2.0.6)

#### Operating system:
Android 0 & 5.1

#### Recording Of The Bug
https://youtu.be/K5kQ-BHbM6Y

**Comment by realrufans** [comment]
It was reproduced ?

**Comment by feruzm** [comment]
@realrufans yes and we have pushed a potential fix, update to app will soon go out. Thanks for reporting, please keep them coming if you find any more issues! 👍

**Comment by realrufans** [comment]
Sure I will.
