### ISSUE TITLE
Add a Clear button on the editor's screen

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#421]
Users can clear unwanted title, tags and content at a go.
<img src="https://i.ibb.co/bQjrjJ0/Screenshot-2019-01-14-16-54-45.png" alt="Screenshot-2019-01-14-16-54-45" border="0">

**Comment by feruzm** [comment]
nice, yes... we will need design of Advanced section cc: @fildunsky

**Comment by ue** [comment]
@fildunsky Could you plase give me idea for the button where should I put that? and how should it looks

**Comment by fildunsky** [comment]
Here you are https://zpl.io/aXw79JX

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded

**Comment by horpeyloaded** [comment]
I can't see Clear button @ue
