### ISSUE TITLE
Push Notification does to save it setting on exit

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#422]
After user's turn off push notification from settings, it turns on automatically after user's exit and relaunch the app. 
`It does not keep it setting like the Dark Theme option does`

**Comment by fildunsky** [comment]
I also have this bug. Plus when I am switching notifications off they are still keep coming.

**Comment by feruzm** [comment]
@horpeyloaded and @fildunsky let's move this to priority, but @horpeyloaded would you mind creating separate issue about additions for customized push notification, because that's bit more involved change that requires backend changes so having it on separate issue would be best to keep track.
