### ISSUE TITLE
Sort comments by votes, age and reputation 

### ISSUE THREAD

**Issue by umair1209** [esteemapp/esteem-mobile#426]
There is no option to sort comments on the new version. It just shows the trending comments.

**Comment by ue** [comment]
I could not reproduce this issue I checked code block when filter is change all data goes empty therefor its not able to do that @feruzm @umair1209 Could you please re-test again thanx

**Comment by horpeyloaded** [comment]
@ue presently users can only filter by **Trending** but other options need to be provided: Filter by
- trending (vote weight)
- age (time of posting)
- reputation (users reputation)

This is possible, other UI has it

**Comment by feruzm** [comment]
@ue Surfer has this, please check it's source code
 
![image](https://user-images.githubusercontent.com/3015990/52779625-36b7a500-3051-11e9-8a90-6b7c54b31360.png)

**Comment by ue** [comment]
I confused that was another Issue that was a misunderstanding. I didn't say its not possible or something. Thanx Feruz

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @umair1209
