### ISSUE TITLE
[BUG]  Reward value always shows in USD in spite of changing USD to BTC from Setting section- eSteem Mobile v2.0.6

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#432]
**Describe the bug**
Reward value always shows in USD ($) in spite of changing USD to BTC from Currency Setting section. Actually, if we change the default currency to any other then the reward values should change according to the newly selected currency. I found this bug in the latest eSteem mobile v2.0.6 when i was checking function of currency setting.

**To Reproduce**
1. Launch the app
2. Click on 'Profile image which is situated in the upper left corner then you will see the setting menu click on that and change currency from USD to BTC. press the back button to come out from setting menu.
3. After changing done see the profile page.
4. You can see the error there because the reward value will not change from USD($) to BTC.

**Expected behavior**
I had expected that the reward value should appear as per the selected currency only as i changed from USD to BTC but the reward value was showing still in USD.
**Screenshots or Video**
https://youtu.be/xDuW2MGV62I

**Smartphone (please complete the following information):**
 - Device: [Samsung J6]
 - OS: [Android]
 - Version [8]

**Additional context**

**Comment by feruzm** [comment]
Thanks for reporting, we will work on this in future updates.
