### ISSUE TITLE
Esteem V2 Video Implementation

### ISSUE THREAD

**Issue by yemmighto** [esteemapp/esteem-mobile#433]
### Project Information 
- Repository 
https://github.com/esteemapp/esteem-mobile

### Project Name 

Esteem Mobile V2

Publisher: Esteem Mobile app 

#### What I Expect

Downloading and login to the new esteem V2 app, I saw the video button option which I thought will be working for video upload or live video recording 

#### The Actual Behavior 
Was surprised when it took me to camera with no video option which suppose not be because there is a camera button option too

 ![image](https://img.esteem.ws/cjbd9wc4eq.jpg)

#### To Reproduce Bug
- login to your new esteem V2 app 
- click the plus sign button below
- click the video button option (as you can see in the screenshot) and see the results 

#### Bug Recording 
https://youtu.be/012h4P-1JxI

**Comment by horpeyloaded** [comment]
This is normal cuz the feature is not implemented.

**Comment by yemmighto** [comment]
Am actually just hearing it is not implemented, not all knew about it been implemented and most will only think it isn't working. If not implemented yet, it can be removed so as not to cause confusion among esteem users

**Comment by feruzm** [comment]
since app is still in beta mode, it is ok to have message saying it is not implemented yet. though thank you for noting it, we will be working on video upload in future updates.
