### ISSUE TITLE
[BUG] Able to make tag input field disappear

### ISSUE THREAD

**Issue by tobias-g1** [esteemapp/esteem-mobile#436]
**Describe the bug**
A user currently has the ability to delete the tag input field therefore if accidentally deleted the user doesn't have the ability to enter tags within the application. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to create new post page
2. Within the tag field, enter the letters "te"
3. Press the backspace button 3 times

**Expected behaviour**
If the user deletes their tag, the tag input option should always remain on the page, thus providing the user with the ability to add tags to their post. 

**Screenshots or Video**
![tag-delete](https://user-images.githubusercontent.com/17148879/51213838-f3fc9300-1913-11e9-98ca-62c165a4c4dd.gif)

**Smartphone (please complete the following information):**
- OS: Android 8.0.1
- Version 2.0.6

**Comment by horpeyloaded** [comment]
This is similar to the tag issues reported here https://github.com/esteemapp/esteem-mobile/issues/313

**Comment by tobias-g1** [comment]
Ok, @horpeyloaded to be fair the image does relate to the same thing, however, the image you added is both not related to the title and not detailed. A code tag is <code> and therefore not actually related in theory to actual tags so impossible to find that duplicate without entering all issues haha.

**Comment by horpeyloaded** [comment]
@tobias-g1 if you check the issue correctly, I was not the one who created it. I only added some extra info (comment) about tag issue which is related to this issue. Meanwhile, the title is different form this so you're right.

**Comment by horpeyloaded** [comment]
No problem @tobias-g1, it was fixed because of this issue you opened. Keep up the goos work as well!
