### ISSUE TITLE
[BUG] Landscape Styling Issues

### ISSUE THREAD

**Issue by tobias-g1** [esteemapp/esteem-mobile#437]
Although issue such as these is to be expected at the current stage of development, I thought it would be a useful task to list a few out. 

**Describe the bug**
There are a number of areas in the application that don't render well when used in landscape mode. 

**To Reproduce**
1. To reproduce the issues mentioned within this issues, please rotate your phone into landscape view and navigate to the page shown within the screenshot. 

It seems that some of these issue are only present when you launch the application in potrait and then switch to landscape aftering logging in, if you launch the application in  landscape some of theses aren't present. 

Issue List

- [ ] Search Field not clickable on home page, when attempting to press nothing happens
- [ ] Gray box appears at the top of the page
- [ ] Bottom bar doesn't resize

The issues mentioned above can be seen in the following screenshot:
 
![image](https://user-images.githubusercontent.com/17148879/51214353-923d2880-1915-11e9-82d3-26657746cc49.png)

- [ ] Profile page doesn't resize to fit full width of screen

![image](https://user-images.githubusercontent.com/17148879/51214527-1a233280-1916-11e9-9147-16a4daae08b6.png)

- [ ] Buttons on pin page overlap with one another

![image](https://user-images.githubusercontent.com/17148879/51214617-5060b200-1916-11e9-83c3-f2e0c3418335.png)

**Comment by horpeyloaded** [comment]
Landscape is currently disabled on the app @ue isn't it?

**Comment by feruzm** [comment]
@tobias-g1 and @horpeyloaded yes landscape mode will be disabled with next update, we will work on Landscape support at later stages. 828632aa7ce31f5d7c63fed83ca83c741b172ea8
