### ISSUE TITLE
Sorting posts does not work properly. 

### ISSUE THREAD

**Issue by umair1209** [esteemapp/esteem-mobile#438]
While sorting posts, trending, hot, created and prompted are working but the rest like active, votes and children are not working.
You just get a blank screen when you choose either of the three. 

**Steps to reproduce**
- Launch the app
- Click on popular posts 
- Sort by active, votes or children option, nothing will be displayed in the screen.

**Comment by umair1209** [comment]
I did check other nodes and I got the same result. None of the nodes are showing posts when sorted with active, votes and children option.

**Comment by umair1209** [comment]
Yes it is working after restarting the app.
A minor bug maybe.

**Comment by feruzm** [comment]
let's create separate issue for tracking server change issue that's more relevant.
