### ISSUE TITLE
[BUG] Voter Info doesn't sort after first use

### ISSUE THREAD

**Issue by tobias-g1** [esteemapp/esteem-mobile#439]
**Describe the bug**
The voter info table does not sort after the first use, you have the ability to sort the table once, however, when a user attempts to sort again, this does not work. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to your feed and find any post that has had 5 or more votes.
2. Click on voter icon shown on the bottom of the postcard
3. Note that when you enter the page that the table is sorted by rewards, the highest STU contributions are shown at the top.
4. Click on the sort option shown at the top left of the page, you will be presented with three options (rewards, per cent, time).
5. Click on per cent. 
6. Note that the table now resorts to show the voters with the highest vote percentage. 
7. Repeat step 4 and select rewards. 
8. Note that the data in the table does not resort. 

**Expected behavior**
The table data shown in the voter info pages should reflect the sort method chosen by a user.

**Screenshots or Video**
![sort_order](https://user-images.githubusercontent.com/17148879/51218374-fc5cca00-1923-11e9-8de8-eb98b78893fe.gif)

**Smartphone (please complete the following information):**
OS: Android 8.0.1
Version 2.0.6

**Comment by feruzm** [comment]
good catch, thanks @tobias-g1 for reporting! we will work on this in future updates 👍
