### ISSUE TITLE
[Feature-request] Add ''delete comment'' option

### ISSUE THREAD

**Issue by umair1209** [esteemapp/esteem-mobile#443]
While there was a presence of delete comment option in the previous version, the new version came without it. There should bean option to delete our own comments .
Moreover it should only allow deleting by author himself if comment doesn't have any votes and/or any sub-comments.

**Comment by feruzm** [comment]
**Technical note:** Deleting post or comment button should show only if comment doesn't have any votes or replies on it.

**Comment by ue** [comment]
example https://github.com/esteemapp/esteem-surfer/blob/legacy/src/services/steem-authenticated.js#L295
