### ISSUE TITLE
App crashes upon re-opening after setting the server to https://steemd.privex.io and closing the app

### ISSUE THREAD

**Issue by umair1209** [esteemapp/esteem-mobile#444]
**Describe the bug**
After setting the server  as ``https://steemd.privex.io`` and closing the app in background, eSteem v2 crashes once it is opened again.

**To Reproduce**
1. Launch the app
2. Go to settings and set the server as https://steemd.privex.io
3. Exit and close the app in background
4. Re-open the app and wait for some time, a crash will occur and you won't be able to open the app again unless you clear the data of he app.

**Expected behavior**
The app should not crash after we set the server to https://steemd.privex.io and reopen it after closing.

**Screenshots or Video**
https://youtu.be/aSSL63jFWBE

**Smartphone (please complete the following information):**
 - Device: Redmi 3S Prime
 - OS: Android 6.0.1

**Comment by feruzm** [comment]
relevant issue: #471
