### ISSUE TITLE
[Feature request] Suggestion: Add Clear all feature in eSteem mobile v2

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#445]
My proposal is to add a useful feature in the composition section so that users can more reliable. Actually this app keeps previous post data in the composition section and when user again visit in composition section to create new post then he has to first delete previous post data (texts & Images links) and tags one by one to make this space free to write new blog, since there is no option available to clear all texts, image and tags in one tap/click hence need to add *clear all* option is specified section. Select all options comes there but if i keep taping on text but it works only for texts & images link not able to remove previous post's tags. This feature was in esteem v1.

Please refer below video for more:
https://youtu.be/jnF-VVi0SgE

**Comment by feruzm** [comment]
#458 is also related!

**Comment by ue** [comment]
Duplicate with #458
