### ISSUE TITLE
[BUG] [eSteem Mobile] 2.0.6 - App Crash when Claiming Rewards

### ISSUE THREAD

**Issue by louis88-steemit** [esteemapp/esteem-mobile#454]
#### Project Information
* Repository:
https://github.com/esteemapp/esteem-mobile
* Project Name: eSteem Mobile
* Publisher (if applicable): esteem.app 

#### Expected behavior
My expectation when I wanted to claim the reward in the app was that my unclaimed rewards will be credited to the account. 

#### Actual behavior
Right now, if you click on the reward, the app crashes and closes. I have created a video for this purpose

#### How to reproduce
Log in to the latest version of eSteem Mobile's mobile app with your Account - Navigate to your wallet under: Profile -> Third Tab -> Wallet. If you have unclaimed rewards, click on the blue area to pick up your rewards. The app closes immediately after the click.

* Browser/App version: 2.0.6 (Latest App Version from Playstore)
* Operating system: Huawei Mate 10 Pro - Android Version 9

#### Recording Of The Bug
Video on Youtube:
https://www.youtube.com/watch?v=n9CTN_nQUAQ

GIF:

![](https://i.imgur.com/Jd1ddBZ.gif)
https://i.imgur.com/Jd1ddBZ.gif

**Comment by feruzm** [comment]
It looks like it was fixed #346, @louis88-steemit can you double check and make sure you are using latest v2.0.6?

**Comment by feruzm** [comment]
Also are you logged in with steem connect or without?

**Comment by louis88-steemit** [comment]
Just tried logged in with steemconnect to claim the reward -> App crashed
Logged in with normal Username and Active Key -> App crashed

**Comment by realrufans** [comment]
I'm on Android 0 and I claimed Reward and hour ago. Everything worked perfectly.

---

He said he used Android 2.0.6

**Comment by tobias-g1** [comment]
It's a strange one, basically on my first attempt I attempted to claim rewards and it worked, the option to claim the reward didn't disappear and then upon clicking it again it crashed, but then shortly after it did work as expected when I attempted to claim a reward. 

There must be some pre-conditions missing that are unknown and likely needs some more investigation. 

Testing on Android 8.0.1, Version 2.0.6

**Comment by fildunsky** [comment]
I've another similar issue with claim rewards on 2.0.7
After claiming reward Claim button stays on screen and if I try to claim again app crashes. Galaxy S8, Android 9.

**Comment by ue** [comment]
Updated. Closing this issue. Should check again with 2.0.8
