### ISSUE TITLE
Account Estimated balance indicates $0

### ISSUE THREAD

**Issue by realrufans** [esteemapp/esteem-mobile#457]
#### Expected behavior

I expect an account estimation value to display the total sum of steem, steem power, Steem dollars and steem available in savings.

#### Actual behavior

An account estimation value is displayed as 0$ even when there are available steem & steem dollars.

#### How to reproduce

* Launch app.
* Click on wallet icon from the bottom right.

#### Bug
![Screenshot_20190117-201736.png](https://cdn.steemitimages.com/DQmZue5STXSbPTxpRt1iTkbZCEcmrSpv1EM7uCS4RyVvSqf/Screenshot_20190117-201736.png)

#### Browser/App version: 
  eSteem Mobile V2 (V2.0.6)

### Possible Fix
I have little idea on codes. So my findings might be totally wrong.

After checking [UserWallet.jsx](https://github.com/steemit/condenser/blob/master/src/app/components/modules/UserWallet.jsx) from steemit/condenser, i was able to see the lines of codes that displays user's estimated value.

When i checked [wallet.js](https://github.com/esteemapp/esteem-mobile/blob/master/src/utils/wallet.js), on esteemapp/esteem-mobile repo, i wasn't able to see any code to display same output.

Here is the code i copied from  [UserWallet.jsx](https://github.com/steemit/condenser/blob/master/src/app/components/modules/UserWallet.jsx) from steemit/condenser.
```
// set displayed estimated value
        const total_sbd =
            sbd_balance +
            sbd_balance_savings +
            savings_sbd_pending +
            sbdOrders +
            conversionValue;
        const total_steem =
            vesting_steem +
            balance_steem +
            saving_balance_steem +
            savings_pending +
            steemOrders;
        let total_value =
            '$' +
            numberWithCommas(
                (total_steem * price_per_steem + total_sbd).toFixed(2)
            );
```

#### Operating system:
Android 0 & 5.1

#### Recording Of The Bug
https://youtu.be/QTm62zlGlOg

**Comment by feruzm** [comment]
Thanks @realrufans for reporting and suggestions on where to look. We will follow up soon.

**Comment by feruzm** [comment]
I created #478 to keep track of that estimated value issue. This is not relevant anymore... Thanks!

**Comment by realrufans** [comment]
My bad! I thought that was estimated balance 🤦. 

My post should have just talked about esteem app not showing estimated balance. Instead of referring it to the 0$ displayed.

**Comment by feruzm** [comment]
All good, please keep up the bug hunting, we are discovering a lot of small but very useful feedback. With each update we will eventually flash out all these and continue adding new features! Thanks! 😉
