### ISSUE TITLE
Suggesting Steem Dapp Advertisements to Esteem app

### ISSUE THREAD

**Issue by yemmighto** [esteemapp/esteem-mobile#465]
### Project Information

- Repository
https://github.com/esteemapp/esteem-mobile

#### Components

**Project Name: Esteem Mobile V2**

**Publisher: Esteem Mobile app**

#### Proposal Description
I am here to suggest that esteem V2 app should implement a steem advert on the app. There are lot of apps that do use advert which mainly is Google advert but here am not suggesting Google adverts on esteem app, steemit as a community has lot of dapps  and tasks on the platform which not all Steemian will know about them. And most member are using esteem app, this can easily make the be aware of it through esteem app.

#### Mock Example 

![image](https://img.esteem.ws/zhhxi7jxw2.jpg)

For it to be convenient for users, this advert can be placed at the top or even below according to the mock sample.

#### Benefits

- this will create more visibility for most dapps who are actually looking for means to reach all Steemian

- this will bring to Esteem member notice the available dapps the can participate in

- this can make esteem app to be more monetize at some point

**Comment by horpeyloaded** [comment]
@yemmighto do check the correct repo for your contributions, this repo is for mobile not Surfer. The screenshot you provided is related to eSteem Surfer app.

**Comment by horpeyloaded** [comment]
@yemmighto it's cool here.

**Comment by yemmighto** [comment]
Thanks, just to pass the suggestion around, it can be implemented on both to create more visibility.

**Comment by feruzm** [comment]
@yemmighto thanks for suggestion! we have some plans on promoted posts which is not priority next few weeks but we have this certainly in mind. we will prioritize accordingly.

**Comment by mistikk** [comment]
@feruzm can you check again, we already implemented to promoted posts feature

**Comment by feruzm** [comment]
yes, we did. So this can be closed, we are exploring other options to give more exposure to promoted posts, but it will be improvement on existing system already.
