### ISSUE TITLE
Opening notification should take user directly to content they are being notified about. 

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#466]
**Describe the bug**
With push notifications enabled, I should receive notifications of most activities that's related to to my profile. Notifications ranging from upvotes, to comments, mentions etc. The notifications come in accurately. 
Opening these notifications launches the app, but doesn't take me to what I'm being notified about. 

**To Reproduce**
Trying to reproduce the bug is quite tricky. Naturally, you will have to receive a notification of an activity first. But this can be artificially done by asking a friend to perform an activity on your profile. Either an upvote or a comment. When the notification pops up on your navigation bar
1. Click on notification
2. The app opens
3. Enter password or pin
4. Feeds is displayed instead of the content of activity you were notified of. 

**Expected behavior**
I expected that when I get notified of an activity, I should be taken directly to the content where that activity was performed and not the feeds page. 

**Screenshots or Video**
As at the time of filing this report, there was no notification. I could not generate one artificially because my friends are asleep. 

 - Device: Xiaomi Redmi Note 5 pro
 - OS: Android 
 - Version: Android Oreo (8.1)

**Comment by feruzm** [comment]
@HarryHeights Thanks for reporting, for now it forwards user to Activities/Notifications page but we have exact same behavior on our todo list.

**Comment by mistikk** [comment]
@feruzm fixed

**Comment by HarryHeights** [comment]
@ue  I've installed the app. I'm waiting to receive a notification. I doubt if any would come now though

**Comment by HarryHeights** [comment]
I asked a friend to perform an activity on my profile to see if I'd receive a notification.
She did. No notification came through for esteemapp. I received notifications on other apps.
I guess its still broken. Maybe even worse

**Comment by HarryHeights** [comment]
I finally received a notification. Although a weird one. I think the issue has been fixed in this app

**Comment by horpeyloaded** [comment]
@ue not fixed!

**Comment by HarryHeights** [comment]
Truly not fixed as @horpeyloaded  said. I rarely even get notifications.

**Comment by mistikk** [comment]
@HarryHeights @horpeyloaded could you test last version from google play

**Comment by HarryHeights** [comment]
The issue is fixed.
