### ISSUE TITLE
[BUG] Unable to see images using esteem mobile 2.0.6 which are uploaded using busy interface

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#467]
**Describe the bug**
I was checking my feed using esteem mobile v2.0.6 and i saw that in some posts only links appear instead of images and when i check same posts in esteem mobile v1 all images appears properly.

**To Reproduce**
1. Go to 'feed section using esteem mobile v2.0.6 and find out the post which has been created from busy.org interface' Here you can refer @slowwalker posts.
2. Click on 'the post link'
3. Scroll down where you can see only some links of the image instead of real images.

**Expected behavior**
In place of links, there should appear images.
**Screenshots or Video**
First screenshots is from esteem mobile v2.0.06 where images do not appear.
![esteem 2 0 6 bug2](https://user-images.githubusercontent.com/36129744/51458626-dac46e00-1d7b-11e9-827c-9e26f3de20fc.jpg)

And same posts is opening in esteem mobile v1 with all images see below, please.

![esteem 2 0 6 bug1](https://user-images.githubusercontent.com/36129744/51458663-ffb8e100-1d7b-11e9-8969-fce37267d618.jpg)

**Smartphone (please complete the following information):**
 - Device: [Samsung J6]
 - OS: [Android
 - Version [8]

**Additional context**

**Comment by feruzm** [comment]
Thanks for reporting @face2face-utopian!

Quick temporary solution would be to add `https://steemitimages.com/0x0` in front of ipfs links, @ue

**Comment by fildunsky** [comment]
Steempress images are not rendering (you can check @creativecrypto account to test it)
