### ISSUE TITLE
[eSteem Mobile] 2.0.6 [BUG] Incorrect markdown cursor position on Bold and Italic text in editor

### ISSUE THREAD

**Issue by louis88-steemit** [esteemapp/esteem-mobile#468]
Repository: https://github.com/esteemapp/esteem-mobile

**Describe the bug**
The editor in the mobile version of the eSteem app offers the possibility to insert text via click. When inserting a bold text, the cursor jumps to the end and creates the command ``****|`` which is very difficult to use. 

It would be better if the cursor were in the middle of the two asterisks to continue writing. There are two possibilities you can or should change here

- 1  After clicking on the Bold icon the following is inserted with the cursor position:
``**|**`` to also write a Bold Text

- 2 the first click on the Bold icon will insert the first two asterisks
``**|`` and after writing a text and clicking on the icon again 2 more asterisks ``**`` are added to do justice to the markdown.

With variant 2 it already works very well with the code snippet in the editor.

The same as above also happens with italicized text. When inserting an italic text ``**`` is inserted which is also a problem as described above. 

**To Reproduce**
1. Download the Latest Version of eSteem Mobile 2 App for Android
2. Go in to the Editor where you can write a Contribution
3. Hit the Bold or Italic Text Button to Insert the Markdown for these Text-Styles
4. There you see the Problem 

**Expected behavior**
My expectation was that if I wanted to insert a bold or italic text, the markdown would be placed correctly to ensure easy writing in the editor. When inserting the markdown command for code this works very well.

**Screenshots or Video**
Screen Video of Input in the eSteem Mobile Application
![ezgif-4-ff36b1a6e0783123](https://user-images.githubusercontent.com/35930080/51465059-549e2c80-1d67-11e9-9a7b-dea184fc8dbd.gif)

At the eSteem Surfer Application is it working very well
![ezgif-4-5a559b4674eb](https://user-images.githubusercontent.com/35930080/51464873-db9ed500-1d66-11e9-850a-16db4723e35f.gif)

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 10 Pro
 - OS: Android 9
 - Version 2.0.6 latest

**Additional context**
In my personal opinion, it would be appropriate to change it like the Code Snippet, which has to be pressed twice on the Bold or Italic button. This is only my own opinion how to solve it best.

**Comment by feruzm** [comment]
Thanks for reporting we will look into this
