### ISSUE TITLE
Startup isolation for connection dependencies

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#471]
Let's make sure app starts even if there is not internet connection OR if any connection servers are down.

.App can start and then notify user about connection issues and stop all waiting UI components and simple show message/alert user.
.When connection is resumed/enabled, app can auto detect that and reload OR app can offer pull down to refresh to pull data from newly changed connection.
.User data is saved on device so unlock pincode shouldn't require connection also avatar can be cached locally as well.
.Planout details to implement these changes

**Comment by horpeyloaded** [comment]
I love this @feruzm, thanks. This is actually what I meant here https://github.com/esteemapp/esteem-mobile/issues/382
