### ISSUE TITLE
Push Notification Custom Settings

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#472]
Can we have more options like checkboxes for the push notification as some users only want push notification when they have replies only. Getting tons of push notifications for upvote from a curation trail can be annoying at times.

Push button Checkboxes
[ ] Upvote
[ ] Downvote
[ ] Transfer
[ ] Replies
[ ] Follow
[ ] Unfollow

**Comment by fildunsky** [comment]
https://zpl.io/Vkw1WWq
