### ISSUE TITLE
App shows wrong timing of posts.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [esteemapp/esteem-mobile#474]
I recently received an upvote from steemhunt and they commented on my post also. Then i saw in Chrome browser, it shows timing is **2 minutes** ago and when i checked in Esteem app it shows **6 hours ago**.
Lets have a look on this.
**CHROME VIEW:**
![Screenshot_2019-01-21-21-05-00-672_com.android.chrome.png](https://cdn.steemitimages.com/DQmReWJwaqdbpuMstdpAftqPbAEoFXpEz7oTdbEdayVQ31k/Screenshot_2019-01-21-21-05-00-672_com.android.chrome.png)
**Esteem app View:**
![Screenshot_2019-01-21-21-04-35-231_app.esteem.mobile.png](https://cdn.steemitimages.com/DQmWhVq1ewNGAejn2ucsejbSukVqa526rMDfx94CrYGPrNn/Screenshot_2019-01-21-21-04-35-231_app.esteem.mobile.png)
#### System information:
* Android: Redmi Y2/S2.
* Operating system: 8.1.0

**Comment by horpeyloaded** [comment]
Already reported

**Comment by PeerzadaZeeshan** [comment]
Ok....
Thanks for looking to my post.
