### ISSUE TITLE
Tags exploring and searching

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#479]
Search should allow tag exploring as well, just like username search.

Right now, if you add `@` and type something, app will search users for you.
we should allow search of tags with `#` and type keyword and selection of tag should allow filters as well like we talked in #475 . 

There is steem api for tag searching, it can be utilized or our search engine should offer tag search as well, either way we should include this into next release!

**Comment by ue** [comment]
relevant: #434

**Comment by ue** [comment]
@fildunsky @feruzm need after press tag screen design

**Comment by fildunsky** [comment]
Do you mean after this screen https://zpl.io/bAZRW3e you don't really understand how to show search results? IMO we should show it as regular feed but for particular tag/search

**Comment by feruzm** [comment]
I think above screen Fil shared is ok and after you select tag we will need some indicator though @fildunsky for user to show that feed has tag filters in them and it can be cleared to return regular feed for all tags?!

@ue to give you context, try: https://steemit.com/trending/art or https://steemit.com/trending/life or https://steemit.com/hot/life, etc. these are filters with tag, so after selection of tag feed post list will update only and we will have indicator for user to see that they are now browsing with tag selected. For indicator, @fildunsky will suggest something

**Comment by fildunsky** [comment]
After user activated tag search we can show it like this: https://zpl.io/am9YGL9
So similar to user feed but without top user avatar. Search box with tag input stays on screen + pressing the close button returns to user feed or page where user started the search. Later we can easily add communities suggestions and/or other things there to the same page.

**Comment by feruzm** [comment]
That looks great! Not sure you can filter Comments with tags but we can start with only Posts tab and later add maybe from eSteem Search results

**Comment by feruzm** [comment]
moving this to next release cycle
