### ISSUE TITLE
Gif is not playing.

### ISSUE THREAD

**Issue by PeerzadaZeeshan** [esteemapp/esteem-mobile#481]
I recently posted an article in which i posted a gif of my own name and after submitting the post i checked my post i saw Gif is not playing. When i checked in Chrome browser it normally plays and again i checked in this app, it doesn't play.
#### Look at this video:
https://youtu.be/bpJYC3UelPU
#### System information:
* Android: RedMi Y2/S2.
* Operating system: 8.1.0

**Comment by ue** [comment]
WIP in PR
