### ISSUE TITLE
Comments threading

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#486]
Proper handling for too deep comments.

1. We will need to only fetch **one** level comments after you click on `x more replies`. 
What this means: Once user click on this they will see only 2nd level comments and if any of these has more comments under then, we will show `x more replies` on those and after those are clicked 3rd level comments will open.

2. We will create separate page or thread for comments in depth more than 4, (because if comments are too deep inside app cannot handle/show them).
What this means: Once you see 3rd level comment has more replies, we will show `x more replies`, once use opens that comments, we will open comment and its sub comments 4th level into separate page as thread and process continues.

@fildunsky we will need some design considerations, please suggest some options for devs to get/understand idea better

**Comment by fildunsky** [comment]
@feruzm Is it something you are talking about? https://zpl.io/bWg8dek

**Comment by feruzm** [comment]
Yes @fildunsky ! Once 4th deep level is clicked for opening, it should open conversation in separate page to enable easy navigation in deeper parts

**Comment by ue** [comment]
@feruzm  Done.

**Comment by feruzm** [comment]
got any screenshot? I will test it bit later though

**Comment by mistikk** [comment]
@feruzm it is already published with prev release
