### ISSUE TITLE
Post Preview or Published Screen Looks Weird than the Previous version

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#490]
There is a serious problem reading posts on eSteem mobile. I've seen different font for different posts. The `center` tag, align right and left don’t work effectively. please check ✔! 

Open these link with the mobile 2:
https://steemit.com/esteem/@good-karma/esteem-mobile-2-0-7-new-features-and-performance-improvements

**Different font from the above post**
https://steemit.com/agfacademy/@dfacademy/dfa-footballers-testimonies-with-new-purchased-football

Android 8
Infinix Note 5
eSteem v1.0.7

**Comment by feruzm** [comment]
@horpeyloaded are you sure you are using v2.0.7? Because I don't see issues, maybe you can illustrate issue with screenshot?

**Comment by ue** [comment]
I guess the post created by using `<div class="text-justify"> bla bla </div>`
thats why its seem like that. 
![screen shot 2019-01-23 at 15 35 26](https://user-images.githubusercontent.com/9980498/51607061-ae982100-1f24-11e9-807d-9bcc5ede63fa.png)

**Comment by horpeyloaded** [comment]
There are issues with the the second post  linked down https://steemit.com/agfacademy/@dfacademy/dfa-footballers-testimonies-with-new-purchased-football

<img src="https://i.ibb.co/GnVXH5F/Screenshot-20190123-142527.png" alt="Screenshot-20190123-142527" border="0">
<img src="https://i.ibb.co/j5M9SkT/Screenshot-20190123-142547.png" alt="Screenshot-20190123-142547" border="0">
<img src="https://i.ibb.co/k9hQjqZ/Screenshot-20190123-142517.png" alt="Screenshot-20190123-142517" border="0">


### On Steemit
<img src="https://i.ibb.co/vVR9tNR/Screenshot-20190123-143052.png" alt="Screenshot-20190123-143052" border="0">
<img src="https://i.ibb.co/SVYqKGN/Screenshot-20190123-143056.png" alt="Screenshot-20190123-143056" border="0">
<img src="https://i.ibb.co/Lrmskjs/Screenshot-20190123-143044.png" alt="Screenshot-20190123-143044" border="0">
<img src="https://i.ibb.co/qmm3nxh/Screenshot-20190123-143048.png" alt="Screenshot-20190123-143048" border="0">

**Comment by feruzm** [comment]
screenshots are helpful, we will investigate further ;)
