### ISSUE TITLE
Invalid Symbol in Following and Follower Texts

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#491]
![](https://i.ibb.co/HYKrL5b/Screenshot-2019-01-23-13-23-50.png)
![](https://i.ibb.co/8B7rj8N/Screenshot-2019-01-23-13-24-06.png)

**Comment by feruzm** [comment]
I don't see this symbol but I see some extra space which can be removed... thanks for report!

**Comment by ue** [comment]
@feruzm where is the extra space?

**Comment by feruzm** [comment]
@ue After number, on iOS I see `(123 )` which means maybe there is some typo or extra space or symbol which is not recognized by Android @horpeyloaded mentioning... please double check to be sure
