### ISSUE TITLE
[BUG] eSteem Mobile v. 2.0.7 - Wrong Upvote Value Calculation / Display

### ISSUE THREAD

**Issue by louis88-steemit** [esteemapp/esteem-mobile#495]
**Describe the bug**
When logged in to the latest Version of the eSteem Mobile Application the Vote-Value of the current Logged in User may looks wrong. In my Test-Case it where a 

``100% Vote`` -> Voting with ``0.00009`` Value
but i think the correct Value that has to be on the Upvote Box should be like:
``100% Vote`` -> Voting with ``0.00032`` Value 
See the Screenshots. I have rechecked the Value of the Upvote by looking at the SteemWorld Entries for the Vote i have done on the eSteem App.

![screenshot_20190123_133802_app esteem mobile](https://user-images.githubusercontent.com/35930080/51607719-c1572980-1f15-11e9-984c-1778fbbce00b.png)

![bildschirmfoto 2019-01-23 um 13 40 29](https://user-images.githubusercontent.com/35930080/51607682-a84e7880-1f15-11e9-8ff7-bb75bf395961.png)

And as u can see here the Official Vote from SteemWorld is much higher as 0.00009
![bildschirmfoto 2019-01-23 um 13 50 18](https://user-images.githubusercontent.com/35930080/51607785-f5cae580-1f15-11e9-823f-f091c155dbe7.png)

In this Example the User @louis.random has upvoted a Contribution of @louis88
Both: The Website steemworld and the App eSteem are set to show USD Prices.

**To Reproduce**
1. Download the latest Version of the eSteem Mobile App from the Playstore
2. Log in to your Account
3. Go and Vote a Post
4. A Slider is appearing where u can see the Vote Value
5. Go and hit the Vote
6. Check the Blockchain Entry with the Value that u have Upvoted

**Expected behavior**
My expectation was that my actual upvote value would be displayed as the value specified.

**Screenshots or Video**
Above.

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 10 Pro
 - OS: Android 9
 - Version of eSteem: 2.0.7 (latest)

**Additional context**
The display of many 0 values can also confuse the user. In my opinion it would be better to display an upvote value with max. 2 or 3 decimal places.

**Comment by feruzm** [comment]
Thanks @louis88-steemit for report! Are you sure Steemworld's calculation is correct and up to date? Because Mobile and Surfer uses same calculation on vote value, we can double check of course.

**Comment by louis88-steemit** [comment]
The eSteem Surfer App shows the correct Value which is at 100% 
![bildschirmfoto 2019-01-23 um 14 37 46](https://user-images.githubusercontent.com/35930080/51610258-97553580-1f1c-11e9-98e5-43f34a826450.png)
0.00034 and not 0.00009

**Comment by feruzm** [comment]
ok, thanks we will check it out!
