### ISSUE TITLE
Reward history is not aligned properly and shows long numbers

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#496]
I thought this was fixed!

#### Expected behavior
The rewards should be shorten to three decimal places e.g 0.001 and properly align to the right.

#### Actual behavior
Does not align to the right properly and shows long range of numbers

![](https://i.ibb.co/qsVBnTf/Screenshot-2019-01-23-13-51-55.png)

#### How to reproduce
- Login app
- Go to Wallet
- Check **reward history** 

* App version: v2.0.7
* Operating system: Android Infinix Note 5 v 8.1.0

***

**Transfer looks perfect**
![](https://i.ibb.co/7WY52Rv/Screenshot-2019-01-23-13-52-33.png)

**Comment by feruzm** [comment]
Nice @horpeyloaded ! We have wallet page improvements this week so this should be suited with this work #478

**Comment by mistikk** [comment]
Which account did you see that, is it horpey? I couldnt repreduce on any account @horpeyloaded

**Comment by horpeyloaded** [comment]
@mistikk yeah, on my account @horpey and the same applicable to any account I logged in.

**Comment by horpeyloaded** [comment]
@mistikk I just checked again and I made a gif 

Android
Infinix Note 5

https://i.ibb.co/R3W9FP3/G-20190125-0935582.gif
