### ISSUE TITLE
Favourite Icon Does Not Indicate a User Already on the List

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#499]
#### Expected behavior
I expect the app to highlight the favorite indicator (♥) if a user is already added to the favorite list.

#### Actual behavior
The app does not indicate if a user is already on the favorite list when you visit the user's profile and clicking the favorite icon again multiplies the username on the favorite panel.  

#### How to reproduce
- Open app.
- Search for a user you want to add to favorite list.
- Visit the user's profile and tab the favorite indicator ♥  to add the user to your favorite list.
- Verify if the user was successfully added by navigating to *Bookmark* on the Menu list and swipe to the right then you see all your favorite list.
- Visit the user's profile again.

* App version: v2.0.7
* Operating system: Android 8

#### Recording Of The Bug
https://i.ibb.co/WnSB6k4/G-20190123-2152492.gif

**Comment by ue** [comment]
@horpeyloaded  can you test it again It should be fixed.

**Comment by horpeyloaded** [comment]
@ue will check thanks.

**Comment by horpeyloaded** [comment]
How do I confirm ✔, I didn't see the builds updated in Microsoft.

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded

**Comment by horpeyloaded** [comment]
Bug occurs again in the latest version

**Comment by ue** [comment]
are you looking hearth icon right because I checked now when you add to favorites a user you seeing red hearth icon instead white @horpeyloaded
