### ISSUE TITLE
Now, Dtube posts are not showing post thumbnails 😫

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#500]
![](https://i.ibb.co/Bf9sG0g/Screenshot-20190123-223204.png)

**Comment by louis88-steemit** [comment]
Yes, I can confirm that. The thumbnail is not loaded at dtube content.

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded
