### ISSUE TITLE
[BUG] Same posts appears twice in Hot & Feed section- esteem v2.0.7

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#501]
**Describe the bug**
Just after update from esteem v2.0.6 to v2.0.7, i was in hot section and i saw some or same posts appearing twice.  Also, the same issue is in the feed section too.

**To Reproduce**
1. Go to 'feed and hot section one by one and scroll down carefully where you can see the error.'

**Expected behavior**
When we check our feed or hot section the same post should not appear twice which is created by one user.
**Screenshots or Video**
For hot section bug please refer the screenshots and for feed section video.
![v2 07-1](https://user-images.githubusercontent.com/36129744/51652190-c6b78100-1fb4-11e9-8f85-28125d9ffa46.png)

![v2 0 7-2](https://user-images.githubusercontent.com/36129744/51652204-d33bd980-1fb4-11e9-9ac2-0241ade8146b.png)

https://youtu.be/kNpm9ZDTpr8

**Smartphone (please complete the following information):**
 - Device: [Samsung J6]
 - OS: [Android]
 - Version [ 8]

**Additional context**

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @face2face-utopian

**Comment by face2face-utopian** [comment]
Thanks 🙏 currently not looking any duplicates posts. hence closing the issue. Thanks to eSteem Team.
