### ISSUE TITLE
[BUG] Used text in reply section also reaches to  post Composition area. esteem v2.0.7

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#502]
**Describe the bug**
If i reply to someone’s post then all texts of reply section are also visible in editor section or composition section.

**To Reproduce**
1. Launch esteem v2.0.7.
2. Enter the login PIN.
3. From your feed section select any post and reply or comment on that post, after successful submission of reply visit post editor or post composition section. 
4. See error ( the all texts whatever you have written as reply or comment are present). 

**Expected behavior**

The texts used for comment in someone’s post should not appear as it is in editor or composition section.  

**Screenshots or Video**
Screenshot is below:

1. The texts from editor or composition section.

![f4d8de82-bcd9-47e5-b912-800de6c496ec](https://user-images.githubusercontent.com/36129744/51663432-cdf28500-1fdc-11e9-8180-9e71e0bba3b9.png)

2. From Reply to section:

![da20520b-0085-471d-bda1-6197f1df1dfa](https://user-images.githubusercontent.com/36129744/51663434-cdf28500-1fdc-11e9-8610-ee9e1eaa8cd6.png)

**Smartphone (please complete the following information):**
 - Device: [Samsung J6]
 - OS: [Android]
 - Version [8]

**Additional context**

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @face2face-utopian
