### ISSUE TITLE
[eSteem Mobile] v.2.0.7 [IDEA] Add NSFW Content Settings / Filter in the Settings Area

### ISSUE THREAD

**Issue by louis88-steemit** [esteemapp/esteem-mobile#503]
#### Repository
https://github.com/esteemapp/esteem-mobile

#### Components
My idea is to create a setting possibility in the app for contents that contain a tag "nsfw" which can either be hidden or adjusted by 3 setting possibilities. This setting is missing so far.

#### Proposal Description
In my opinion the eSteem Mobile App should have the NSFW filter just like other front-ends for the Steem platform. With other applications it is integrated everywhere and also the eSteem app should integrate it. Here it would be possible to add the following possibilities under the settings for the logged in user. This is how NSFW content should be handled:

- Always hide (Disables Content what have the Tag nsfw)
- Always warn (Displays a Warning Message that this Content can be not safe for Work)
- Always show (Do nothing - All nsfw Content will be shown)

The user should be able to select these settings in the settings via a drop-down menu. This function of a drop-down menu is already available and can be extended to select the NSFW content.

In my example screenshot I once illustrated how it can look like in the mobile app. 

#### What is NSFW? (Not Safe For Work)
> Not safe for work (often shortened to the acronym NSFW) is an Internet slang or shorthand used to mark URLs and hyperlinks which link to videos or websites pages containing nudity, intense sexuality, profanity, violence, and/or other potentially disturbing subject matter, which the viewer may not wish to be seen looking at in a public or formal environment, including a workplace or school.
Source: Wikipedia

#### Mockups / Examples
<img src="https://i.imgur.com/o5SsTnV.jpg">

#### Benefits
By allowing the user to choose how to handle NSFW content, it is a great added value for the application and offers users more protection, e.g. at work or at school.

#### GitHub Informations:
https://github.com/louis88-steemit

**Comment by mistikk** [comment]
@feruzm steem api has Nsfw filtering feature?

**Comment by feruzm** [comment]
@mistikk nope, it is UI side filtering only. Check if post has nsfw, xxx, or other abusive words, you can get them from steemit or busy source code as an example and filter those posts with simple placeholder and user has to click on them to see them or use Settings.

**Comment by ue** [comment]
@mistikk Test and close please if its okay or assing the owner
