### ISSUE TITLE
Annoying claim rewards confirmation window after claiming

### ISSUE THREAD

**Issue by fildunsky** [esteemapp/esteem-mobile#506]
Let's disable claim reward confirmation window saying reward was claimed successfully? Maybe we can change it to notification which disappears after 2 seconds which don't expect input from user? I mean in this case there would be no `OK` button and user can continue his business without tapping on this window.

![2019-01-25 02 40 49](https://user-images.githubusercontent.com/32987666/51715673-c964b580-204a-11e9-8309-9efe04a5f96a.jpg)

I mean let's just remove this window?

**Comment by horpeyloaded** [comment]
Apply this to after clicking **publish button** as well. Users don't need the confirm button.

**Comment by fildunsky** [comment]
Sample: https://zpl.io/V4QNWM4

**Comment by feruzm** [comment]
Yes, let's change them to toast messages.

**Comment by mistikk** [comment]
@feruzm fixed and distributed for testers

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @fildunsky

**Comment by fildunsky** [comment]
Works like a charm!
