### ISSUE TITLE
Share post link option only shares the title of the post.

### ISSUE THREAD

**Issue by umair1209** [esteemapp/esteem-mobile#507]
**Describe the bug**
When we select a particular post and try to share it through other apps, only the title of the post is displayed.
**To Reproduce**
1. Select any post of your choice
2. Click on three dots on the right side of the post and select share post
3. Share it through any app
4. You will only share the title

**Expected behavior**
Sharing a post should provide a direct link to the post

**Screenshots or Video**

https://www.youtube.com/watch?v=6Pwo4QKa86s
**Smartphone (please complete the following information):**
 - Device: Redmi 3S Prime
 - OS: Android 6.0.1

**Comment by horpeyloaded** [comment]
@feruzm I can reproduce that here is a gif
![](https://i.ibb.co/kHjXDBs/G-20190130-1243572.gif)

https://i.ibb.co/kHjXDBs/G-20190130-1243572.gif

**Comment by horpeyloaded** [comment]
Closed!

**Comment by feruzm** [comment]
thanks, Ugur have fixed it, should come out in next update
