### ISSUE TITLE
Enable RN RAM to check if performance improved

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#514]
Now that 2.0.8 will have custom JSCore, let's focus on next improvement to test on 2.0.9. 
>Basically with RAM bundles (Random Access Modules bundle format) you get a few bundle.js files instead of one large file.

So this multiple bundles requires less memory on start up those should improve our startup even further. Check if that's the case, before merging please test on device to make sure.

http://facebook.github.io/react-native/docs/performance#enable-the-ram-format

**Comment by mistikk** [comment]
It is already fixed on release 2.0.8 @feruzm

**Comment by feruzm** [comment]
ok, let's close this... we need to find out if this is causing iOS crash check #563
