### ISSUE TITLE
[BUG]eSteem v2.0.7- Allowing to reblog own content

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#515]
**Describe the bug**
I was testing the reblog feature of eSteem mobile v2.0.7 and try it with my own latest content and saw that the whole process of reblogging completed and also got notification from the app that your post has been reblogged. However, esteem v1 always displays an error message that you can't reblog your own content.

**To Reproduce**
1. Launch the app and enter the required PIN.
2. Click on 3 vertical doted which is situated just right side of the post.
3. Choose the reblog option and click on it then wait for the process completion.
4. You will see a message *Success*. 

**Expected behavior**
As i have mentioned above that there is no process to reblog own content.
**Screenshots or Video**
https://youtu.be/tmmfE7OQo8E
**Smartphone (please complete the following information):**
 - Device: [Samsung J6]
 - OS: [Android]
 - Version [8]

**Additional context**

**Comment by horpeyloaded** [comment]
This has already been reported by Syed
