### ISSUE TITLE
[Feature suggestion esteem app v2] Please Add "Open with" feature to open other steemit link

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#527]
Hi eStem Team,
I would like to see a new feature in eSteem app and that is "open with". Actually, sometimes some bloggers mention a link of the previous post or another steemit link and when we click on that link using esteem app v2 it goes redirect and the link open in the browser so if we would have feature in latest app then we can open that link our app only using "open with* feature. I have tried to show you all an example here:

![img_6222](https://user-images.githubusercontent.com/36129744/52164292-144e8f00-2715-11e9-890e-b3f0f3e4a02c.PNG)

Thanks
@face2face

**Comment by face2face-utopian** [comment]
Yes i said about only steemit link. Thanks for acceptance.

**Comment by feruzm** [comment]
moving this to next release cycle, current one (2.0.8) is overdue

**Comment by horpeyloaded** [comment]
internal parsing of links are not working.

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @face2face-utopian
