### ISSUE TITLE
[Feature enhance esteem v2] Pleae add "Transaction alert" in Notification section

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#529]
Currently, we get the notifications for upvote, reblog, mentions, reply and follow but it will be better if there is one more option as transaction alert. If someone transfers or a user self-transfer to another account some amounts then we should have a notification that you have received ...steem or .. sbd OR .. steem has been transferred from your account to @...... account.

I have tried to the suggestion by an image where i have placed the suggestion in rectangular shape.

![transfer notification](https://user-images.githubusercontent.com/36129744/52188497-26394a80-2859-11e9-8136-ef1b61f1388c.png)

Thanks
@face2face

**Comment by umair1209** [comment]
Nice . Keep them coming.
