### ISSUE TITLE
[Feature enhancement esteemv2] Default footermessage for posts and comments

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#544]
Dear eSteem team,
I would like to suggest a new feature for our eSteem v2 and that is *default footer message* and it should appear at end of every post or comment by default. However, there will be an option to enable or disable it in the setting section so that users can enable or disable it anytime if they want. Also need to care that the footer message should not appear at editor section when users will create a post or comment but just after submission, the footer message will take place at the end of blog or comment. I have found a proper place for enabling or disable option here:

![screenshot_20190206-174405_esteem](https://user-images.githubusercontent.com/36129744/52342848-83412600-2a3c-11e9-9a56-4e6c7e222f09.jpg)

I would also like to suggest the footer message but if eSteem team wants to replace with any other message then i have no issue. According to me a message should be *Published by eSteem Mobile* if done by eSteem mobile.

Thanks
@face2face

**Comment by feruzm** [comment]
Thank you, looks like created #546 related to this... we have something more in mind for footer messages, and we will share some of our ideas soon.
