### ISSUE TITLE
Server change requires restart

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#547]
Server change requires restart until it starts to use new selected server, which shouldn't be happening...

allow app to disconnect from previous selected server and connect to new server without requiring restart.

Make sure `new Client` is created properly or old one removed properly for this to work...
https://jnordberg.github.io/dsteem/classes/client.html

slightly related to #471, make sure to check this part: 
* User data is saved on device so unlock pincode shouldn't require connection also avatar can be cached locally as well.

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @feruzm
