### ISSUE TITLE
Does the wallet include user's activities ?

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#556]
I can't seem to understand the wallet, if activities are included then there are many things wrong 
Check https://busy.org/@horpey/activity.. This shows the right user's activities.

The wallet history also display some reward numbers which are not understandable and I can only see wallet history of a few days or hours.

**Comment by talhasch** [comment]
There's nothing with esteem.

Seems busy mixes all user records & user activities & wallet history in a single page. 

We serve major part of those data on different parts of our apps. We show some of them to user via activities, some of them on wallet transaction history etc..

We have the data too. I'm not sure if it's useful but we can list all user data like busy on a single page. What do you think @feruzm ?

**Comment by feruzm** [comment]
@talhasch yes, it is time to remove history from wallet pages. Everything user needs should be in activities page. @mistikk and @ue  please make sure mobile also doesn't fetch wallet history on wallet page, it is redundant and unnecessary, information should be shown in activities page via our internal db source.
