### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nawab69** [esteemapp/esteem-mobile#558]
**Describe the bug**
I have found a bug in esteem v2 that, Some server / node don't connect successfully. And another problem is when I go to login with steemconnect,  I saw that steemconnect display halfscreen and half screen is white. There is no adressbar to verify steemconnect url.

**To Reproduce**
1. Go to Settings
2. Click on server
3. click on some server
4. See error (Connection failed)
again.
1.Logout
2.Login with steemconnect
3)See that steemconnect display half and there is no browser link to verify the steemconnect url and SSL

**Expected behavior**
I want every server work properly. If some server don't connect they shouldn't keep in esteem. I expect to see that steemconnect login in full screen with Address bar at the top to verify the steemconnect URL.

**Screenshots or Video**

https://d.tube/#!/v/nawab69/tj4jf7y3

![screenshot_20190209-111137](https://user-images.githubusercontent.com/44573643/52517207-f081d080-2c61-11e9-873e-dbc2da1e708f.png)

**Smartphone (please complete the following information):**
 - Device: Lava Iris 820
 - OS: Android
 - Version 6.0

**Additional context**
I think this is servers problem. This server shouldn't keep in esteem if they are not working.

https://steemit.com/@nawab69

**Comment by horpeyloaded** [comment]
That's the feature for eSteem app and working as it's programmed. If a server is not working at the time, you will be shown a connection failed toast. There are other working servers you can connect to e.g esteem.. 

For Steemconnect there is a problem with the position, the developer will fix it and good suggestion for visible address bar.

@feruzm ☝

**Comment by nawab69** [comment]
Thank you.

**Comment by horpeyloaded** [comment]
The SteemConnect part of this report needs to be addressed @feruzm

> For Steemconnect there is a problem with the position, the developer will fix it and good suggestion for visible address bar.

**Comment by feruzm** [comment]
Thanks @horpeyloaded , moved to proper board to work on...

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @nawab69
