### ISSUE TITLE
[BUG] Wrong Links on own Profile - Drop Down Links for Reply, Bookmark and Share

### ISSUE THREAD

**Issue by louis88-steemit** [esteemapp/esteem-mobile#560]
**Describe the bug**
If you are logged in to the app and go to your own profile and try to perform various actions from a written post there, this will fail. If you click the drop-down button of a post you wrote yourself, you have the following choices:
- Copy the link to the post
- Reply to the post
- Share the post in another app
- Bookmark the article

If you press link to copy everything is fine. But if you reply to a post or press the other buttons, the correct will not happen. The following happens

- Reply is linked to the Reblog Feature (Which should also not available for own Posts)
- Share is linked to Reply to the Post
and
- Add to Bookmark is linked to the Share Feature.

**To Reproduce**
1. Log in to your Steem Account by using the latest Version of the eSteem Mobile App
2. Go to your own Profile
3. On the Upper Right Side of the Post Hit the three Points to Open the Menu
4. Try to Bookmark , Share or Reply your own Post

**Expected behavior**
If you call the options for your own post, I assume and expect that exactly the function is deposited, which is also displayed.

**Screenshots or Video**
Youtube Hosted Video / Screen Video that shows the Issue
https://www.youtube.com/watch?v=VfLTMgaDcDY

**Smartphone:**
 - Device: Huawei Mate 10 Pro
 - OS: Latest Andrpid Version
 - Version of eSteem: v.2.0.8, 839

**Additional context**
I think that this will also show the options that are available for other posts. (contributions of other users) and here no special reprogramming was carried out like with own contributions one deals.

**Comment by feruzm** [comment]
Good find, we will check it out!

**Comment by mistikk** [comment]
@feruzm fixed and distributed for initial testers

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @louis88-steemit
