### ISSUE TITLE
[BUG] eSteem Mobile 2.0.8 - Push Notification Disabled And Still Working

### ISSUE THREAD

**Issue by erikah1** [esteemapp/esteem-mobile#561]
**Describe the bug**
After disabling Push Notification I'm still getting notifications when users are voting on my post which is very irritating. 

**To Reproduce**
1. Launch app
2.  Login your account
3.  Go to Settings and disable Push Notification
4.  Exit and re-launch app
5.  Check the Settings and see the Push Notification still disabled.

**Expected behavior**
App should stop notifications when Push Notification is disabled. 

**Smartphone (please complete the following information):**
 - Device:  Huawei Mate 10 lite
 - OS: Android 8.0.0
 - eSteem Mobile 2.0.8, 839

**Additional context**
Please fix it because it's a huge problem. I have to disable sound.

**Comment by feruzm** [comment]
It should have been fixed with latest release, but we will double check. Thank you for reporting @erikah1 !

**Comment by erikah1** [comment]
Thank you!

**Comment by mistikk** [comment]
@feruzm fixed and distributed for initial testers

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @erikah1

**Comment by erikah1** [comment]
Yes, of course. I'll get back to you soon. 
Thank you!

**Comment by erikah1** [comment]
@ue Unfortunately I'm still getting notifications.

**Comment by feruzm** [comment]
After you disable notifications, could you restart app and see notifications still coming, are you testing latest build @ue shared?

**Comment by erikah1** [comment]
So here's what's happened. I've downloaded the latest version @ue shared here. Push Notification was already disabled but I was still getting notifications. After yesterday's message from @feruzm  I enabled Push Notifications, disabled it again and since then it's working perfectly, I'm not getting notifications any more. My apologies.

**Comment by mistikk** [comment]
@erikah1 Can you remove and reinstall to app, we fixed that bug on last release.

**Comment by erikah1** [comment]
@mistikk Sure, can you give me a link to the app?

**Comment by mistikk** [comment]
You can download from these links @erikah1 
iOS : install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/internal
Android : install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/internal

**Comment by erikah1** [comment]
I've been testing it for 24 hours or so and it's working fine.
