### ISSUE TITLE
Multiple accounts are not stable

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#562]
A user complained about this and I have also experienced it several times now.

Sometimes, the first or second account I logged in is not found on the account list and if I try to login the account I can't find on the list (the missing account) I get this response, and the account shows up while other account becomes hidden. 

![](https://i.ibb.co/K5h5Ngn/Screenshot-2019-02-11-03-49-12.png)

Just weird!

**Comment by feruzm** [comment]
Thanks, this should be double checked asap @mistikk !

**Comment by mistikk** [comment]
@feruzm fixed and distributed for initial testers

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded
