### ISSUE TITLE
iOS crash fix

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#563]
iOS build crashed on startup, build not crashing version for AppStore review.

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @feruzm
