### ISSUE TITLE
Steemconnect notes

### ISSUE THREAD

**Issue by feruzm** [esteemapp/esteem-mobile#564]
On steem connect login mention/add following text.

`Note: Steemconnect may charge some fees from your reward transactions`

ref: https://steemit.com/steemconnect/@fabien/major-incoming-changes-on-steemconnect

**Comment by mistikk** [comment]
After steemconnect login or before open to steemconnect login modal? @feruzm

**Comment by feruzm** [comment]
Before, we have Note section in Login page for Steemconnect, just add above with bold text.

**Comment by mistikk** [comment]
@feruzm fixed and distributed for testers

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers

IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @feruzm
