### ISSUE TITLE
[Suggestion] After tapping on on-screen notification it should redirect and open that notification relevance page directly

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#565]
Dear eSteem team,
I would like to suggest an idea to improve push notification functionality, actually users see notifications on his/her mobile screen first then they tap on that to open that notification only. In current functionality, if a user taps on a reply activity from his/her on-screen notification then instead of opening the reply page the profile page of user goes open hence *i would like to suggest that if user tap on a reply or any other notification from his mobile screen notification center then that notification should redirect properly and should open that page only for which notification was related*.

First look below video for better understanding..

https://youtu.be/4jM2lJJd_co

Also, see the on-screen notifications:
![screenshot_20190211-124513_samsung experience home](https://user-images.githubusercontent.com/36129744/52550971-789ddc80-2e00-11e9-86b1-5f68c8fee459.jpg)

Thanks
@face2face

**Comment by horpeyloaded** [comment]
I think this has already been reported by harry-height

**Comment by horpeyloaded** [comment]
https://github.com/esteemapp/esteem-mobile/issues/466

**Comment by mistikk** [comment]
@feruzm fixed and distributed for initial testers

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @face2face-utopian
