### ISSUE TITLE
Work on Tags

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#569]
Tag texts should not be hidden please. Display it in full text and allow users to scroll between tags for convenience or better make it two lines. 

![](https://i.ibb.co/gvYQ5kG/Screenshot-2019-02-11-12-22-41.png)

Here is a screenshot showing a user not able to publish because of the tag error. I had to tell him to check thoroughly before he figured it was tag error. He can't scroll between tags, and can't see the tag texts in full. Users will make mistake of tags with this previous design.

Text can also be hidden within the tag box like if you click the text it will shift up, please make it fixed like the tag screenshot shown

![](https://cdn.discordapp.com/attachments/385448634197737484/544476726978412565/Screenshot_2019-02-11-19-15-52-417_app.esteem.mobile.png)

Add this circled cross to tags ❌❌
![](https://i.ibb.co/F0G21dd/Screenshot-2019-02-11-12-23-17.png)

**Comment by horpeyloaded** [comment]
I will edit it later if you don't understand my grammar. I have to add other issues before I missed them brb

**Comment by feruzm** [comment]
thanks for reporting, we have decided to simplify tags section. For now you can scroll tags horizontally if you didn't know. next release we will have simple input where tags will be separated by space, nothing fancy just simple input field.

**Comment by horpeyloaded** [comment]
@feruzm I can't scroll horizontally here and  user could not too.

> I'm using mobile app, just realized the new release having trouble to make tags if the previous tags are long, and those at the back weren't able to fit in. Can we make it flexible? Or better yet if the app can switch between horizontal/vertical view?

**Comment by horpeyloaded** [comment]
please can you make it busy design instead of plain text 
![](https://i.ibb.co/gvYQ5kG/Screenshot-2019-02-11-12-22-41.png)

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded

**Comment by horpeyloaded** [comment]
One thing left… Not showing text inside the tag border completely.. Tag should be shown fully

**Comment by horpeyloaded** [comment]
@ue the tag is not perfect and people are complaining about it. Let's go with this by @feruzm

> next release we will have simple input where tags will be separated by space, nothing fancy just simple input field.
