### ISSUE TITLE
Show original link when responding to a reply

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#570]
When replying to a comment via notification, I don't get the option: go to full content or post. I have to go to the person's profile before I can see the main post which I'm getting the notification on.
Could be better if I could just go straight to the post from notifications

Check this link, you will understand what the user meant. 
https://busy.org/@horpey/re-trincowski-re-good-karma-esteem-mobile-2-0-8-speaks-5-more-languages-reward-in-many-currencies-and-more-20190209t033318764z/#@trincowski/re-horpey-2019210t1451510z

On Surfer 🏄
![](https://cdn.discordapp.com/attachments/445901975301914624/543460666330185759/unknown.png)

**Comment by feruzm** [comment]
related: #486

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded

**Comment by horpeyloaded** [comment]
No link user can tab to the original thread.. There is only a summary for post 📬. Check the screenshot above `View the full content`

**Comment by horpeyloaded** [comment]
The replies panel should have an indicator to the original thread as well @ue @feruzm

<img src="https://i.ibb.co/rZRsK0Y/Screenshot-2019-02-26-03-55-10.png" alt="Screenshot-2019-02-26-03-55-10" border="0">

When user tap on the pointed indicator, it will open the thread that owns the reply/comment.

**Comment by horpeyloaded** [comment]
This works perfectly for reply notification

**Comment by ue** [comment]
the summary for post its also clickable link but its seems summary of the post if you click this button you will directly go to original post @horpeyloaded

**Comment by horpeyloaded** [comment]
Go to **Replies** tab, click on reply button. The summary of the post is not clickable.

**Comment by ue** [comment]
its implemented only for notificaiton @horpeyloaded
