### ISSUE TITLE
Link to original thread 

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#571]
I cannot just read the full contents of a reply by just clicking on it.  I have to go to the original post and to the replies section to see the full contents of the reply.

Here is a screenshot 
![](https://i.ibb.co/2Kj34Lf/Screenshot-2019-02-11-12-52-07.png)

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded
