### ISSUE TITLE
Centered Images not fit in

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#572]
#### Expected behavior

I expect my centered images to be displayed horizontally and if the line cannot contain them, they should continue on the second line.

**Steemit Display**
![](https://i.ibb.co/9y1N5NM/Screenshot-2019-02-11-13-02-36.png)

#### Actual behavior

The centered images nested are displayed vertically. 

**Display**
![](https://i.ibb.co/qmD7wCB/Screenshot-2019-02-11-13-04-42.png)

#### How to reproduce

- Open app
- Login
- Open Editor Screen
- incorporate images (2 or more) within a center tag.

**Comment by horpeyloaded** [comment]
https://github.com/esteemapp/esteem-mobile/issues/577

**Comment by ue** [comment]
@horpeyloaded can you put post url if you open issue related with post. for testing

**Comment by horpeyloaded** [comment]
@ue https://steemit.com/eternitas/@horpey/ohiprse-eternitas-promo-banner
