### ISSUE TITLE
Remove reblog option on already reblogged post

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#574]
#### Expected behavior

I expected not to see reblog in the option of reblogged posts.

#### Actual behavior

Reblog option is shown.

![](https://i.ibb.co/XVqbkLX/Screenshot-2019-02-11-13-15-06.png)

#### How to reproduce

- Open app
- Login
- Reblog a post or skip to the next option
- Tab on the 3 dots of a reblogged post
- See reblog option

***
* App version: v2.0.9
* Operating system: Android 8.0.1
***

#### Recording Of The Bug

- -

**Comment by ue** [comment]
Fixed.
