### ISSUE TITLE
Suggestions - Don't Want to Make Issues hectic

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#576]
I want to keep these notes here as the developers are still working on bugs. I will separate them once they start working on features.

***

- Show resteem count on post page.
- Scroll to comment on notification.
- Show unread message count upon app open.

**Indicate if user follows you:** 
- When you visit user's profile
- In **Following list**
![](https://i.ibb.co/QmZnTSq/Screenshot-2019-02-11-13-24-06.png)

- Indicate whom I follow in Follower list.

- Show number of **Mutual friend/follower** in Following and Follower list

- Drag username to arrange 

- Support Fingerprint to unlock

- Show an indicator if selected server is connected (a green ✔)

- Actual time in notification activities

**Comment by ue** [comment]
these are all completed except fingerprint that is already in our list. you can check them as well if you find an uncompleted issue you can reopen this issue. thanx for the feedback @horpeyloaded

**Comment by horpeyloaded** [comment]
Okay, will do. But messaging feature is no longer available in app
