### ISSUE TITLE
Image upload error

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#580]
I experienced it while posting few hours ago. Right after i added a picture and started to type text again.. all my previous text were blocking in blue, if I'm not careful.. it will easily deleted

***
Here, similar issue. After added photo, once wanted to tap on the screen to activate keyboard, a big portion of the editor being automatically highlighted

![](https://cdn.discordapp.com/attachments/385448634197737484/544693730020687872/Screenshot_2019-02-12-09-37-22-960_app.esteem.mobile.png)

**Comment by horpeyloaded** [comment]
https://github.com/esteemapp/esteem-mobile/issues/577

**Comment by ue** [comment]
@mistikk could you please test on android it doing that?

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded
