### ISSUE TITLE
Reply does not save text in local storage

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#581]
#### Expected behavior

I expect the app to save texts typed in reply box to local storage until it's posted.

#### Actual behavior

It doesn't save user's data typed in reply box.

#### How to reproduce

- Open app
- Login
- Visit a post
- Click on reply/comment
- Type words
- Click the back key/move out of the reply box
- Go back to the reply box

**Comment by horpeyloaded** [comment]
https://github.com/esteemapp/esteem-mobile/issues/577

**Comment by feruzm** [comment]
PS. Save reply text temporary on Asyncstorage with `key:author/permlink` and `value:reply content` until content is published. e.g. `AsyncStorage.setItem("${author/permlink}", "this is my reply")` note author and permlink is data of content, user is replying to.

**Comment by feruzm** [comment]
@horpeyloaded now that I think about this, why would we need saving reply into draft? Could you give me practical examples?

**Comment by horpeyloaded** [comment]
If I click on a reply, edit box appears (I type my response), if I click out mistakenly and go back to reply, my typed text would wipe out, considering a user already typed more than 150 words, the typed text would wipe out even undo key wouldn't revive the works. @feruzm

**Comment by feruzm** [comment]
so it should hold comment until submit is clicked, right?

**Comment by horpeyloaded** [comment]
yeah 👍

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded

**Comment by horpeyloaded** [comment]
@ue not fixed in the latest update

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded
