### ISSUE TITLE
post preview bug

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#586]
My esteemapp stopped for more than 3 times while viewing some posts with many photos insideblush .. and photos from other app like busy or steempeak do not show up if I view on esteemapp

**Comment by feruzm** [comment]
Please examples of posts would be really helpful or screenshots. We need to make sure devs can reproduce error/issue to work on them or know what to fix. Thanks! 🙏

**Comment by horpeyloaded** [comment]
It was reported by a user @feruzm

**Comment by horpeyloaded** [comment]
Photo not showing for this post in preview

https://steemit.com/agfacademy/@dfacademy/stndpzj-teaching-decentralized-football-academy-team-ball-control-drill-by-andre-gray-7-mins-video

![](https://i.ibb.co/1MVN3X5/Screenshot-2019-02-13-07-02-42.png)
![](https://i.ibb.co/84SKZtJ/Screenshot-2019-02-13-07-02-32.png)

**Comment by horpeyloaded** [comment]
https://github.com/esteemapp/esteem-mobile/issues/577

**Comment by horpeyloaded** [comment]
<img src="https://i.ibb.co/SwbjX21/Screenshot-2019-02-13-07-16-55.png" alt="Screenshot-2019-02-13-07-16-55" border="0">

https://steemit.com/poetry/@horpey/oswuaik-hope-poetry

**Comment by horpeyloaded** [comment]
Support quote text

```
> text
```

**Comment by ue** [comment]
![Screen Shot 2019-03-31 at 13 11 13](https://user-images.githubusercontent.com/9980498/55287805-81e60700-53b6-11e9-82a2-f1e0b7822e1d.png)

Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded
