### ISSUE TITLE
typing bug

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#587]
My mobile esteem app won't let me type more than 3-4 words before it flickers the keyboard up and down several times then goes to white screen and eventually stops responding. I have started typing up things on a different format and then pasted them into the format box to get posts done.

**Comment by feruzm** [comment]
Could we get clarification on what it means by different format and pasted into format box? Does it mean user using different editor and copy pasting text or does it mean some formatting tags causing flickering issue.

**Comment by horpeyloaded** [comment]
He meant his device keyboard flickers and crashed when he types in eSteem editor. 

And he can only post by typing in another editor then copy and paste into eSteem editor.

**Comment by feruzm** [comment]
thanks, we will need Android version and Device type as well to try to test it on same device and android version with emulator

**Comment by horpeyloaded** [comment]
Sorry, he was using v1. I will close this for now and open if he reproduces it that on v2.
