### ISSUE TITLE
Tag border doesn’t show completely

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#588]
It would be better if the bottom tag borders can be shown completely, it doesn't look too good if a post has no comment.

![](https://i.ibb.co/HpNcgJk/Screenshot-2019-02-12-21-34-50.png)

**Comment by mistikk** [comment]
@feruzm fixed and distributed for initial testers

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded
