### ISSUE TITLE
Open Steem Link (when app is already launched / opened)

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#590]
How do I open Steem links [https://steemit.com/life/@horpey/helping-others-e0d34dfe8605f] (Busy, Steempeak...) I tried pasting in the search buy didn't work.

@feruzm

**Comment by feruzm** [comment]
this should've been part of this #475, but we will work on this separately because it is slightly different approach

**Comment by mistikk** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @horpeyloaded

**Comment by horpeyloaded** [comment]
@mistikk Please check this https://github.com/esteemapp/esteem-mobile/issues/643

**Comment by mistikk** [comment]
@horpeyloaded Oo thank you I didnt see that, I fixed I will share build link for test after merging pr

**Comment by horpeyloaded** [comment]
Does not open post link one clicked @mistikk

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
