### ISSUE TITLE
Feedbacks (High Priorities)

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#594]
Please work on all these before the next release even it will take some time. The app needs to be perfect in the next stage now. 

- Log in, go to left menu, then setting. Next if you click the plus button besides username (top of menu) the combo displays my user name 2 times

- When I'm connected by wifi but without internet, the pin screen doesn't appear and I can click and create new post.

#### Suggestions:
- Search results is shown always in dark skin mode 🎈

- In dark mode, inactive links like tabs maybe could have more contrast 🎈

- When a menu option is selected and I click again nothing happens, maybe if it was highlighted will be fine

#### Leaderboard view
- To open users view, the only area to click is user image. As user I expected to open user details making clik over username 🎈

- I'm not sure if is important, but this view has not update feature (sliding down the list on the top) 🎈

#### Search tool:
- I can't go back using physical back button 🎈

#### Feed view

- when I scroll on images, some times the image blinks

#### General

- When I change app using "alt & tab" physical button, the post detail view is shown empty (for example clicking over a search result) 🎈

- When try to edit a post from Musing.io, it stuck on eSteem wallpaper, got to clear and reopen the app to use it. 🎈

- When open a post from Instagram via Share2Steem, the image does not appear, only show the source link. 🎈

**Comment by feruzm** [comment]
@ue review these and do part of this in this release cycle 2.0.9 and part of it we will move to 2.1.0

**Comment by ue** [comment]
I will fix related Leaderboard Could you please take a look `* I can't go back using physical back button` this. @mistikk

**Comment by mistikk** [comment]
Back button issue fixed

**Comment by ue** [comment]
@horpeyloaded @feruzm Could you guys can test and lets remove from content fixed one. lets move for next release

**Comment by ue** [comment]
@horpeyloaded  could you please separete which is not fixed yet create as new issue  I am closing now

**Comment by horpeyloaded** [comment]
I think most is fixed in the latest version @ue
