### ISSUE TITLE
Weird Space After HTML Heading and the Next Words

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#596]
#### Expected behavior

It is expected for the app to show any word typed after HTML heading tag in next line after a blank space.

**Steemit Preview**
<img src="https://i.ibb.co/ZM6D7dB/Screenshot-2019-02-14-07-54-58.png" alt="Screenshot-2019-02-14-07-54-58" border="0">

#### Actual behavior

It shows a scary space after a HTML heading tag.

**NB:** This works perfectly with a Markdown heading syntax. 

**eSteem Preview**
<img src="https://i.ibb.co/fnLh5p8/Screenshot-2019-02-14-07-54-36.png" alt="Screenshot-2019-02-14-07-54-36" border="0">

#### How to reproduce

- Open app
- Login
- Open Editor Screen
- Start you post with a HTML heading tag (h1...h6) and write words after it
```
<h4> Steeem </h4>

Decentralized social media platform
```
- Check the preview

***
* App version: v2.0.8
* Operating system: Android v8.1.0
***

#### Recording Of The Bug
<img src="https://i.ibb.co/YfzBtmm/G-20190218-1417292.gif" alt="G-20190218-1417292" border="0">

**Comment by horpeyloaded** [comment]
https://github.com/esteemapp/esteem-mobile/issues/577

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you.
