### ISSUE TITLE
[eSteem mobile v2 ios] Share is working as reply and reply is working as reblog.

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#601]
**Describe the bug**
I was in my profile section. I clicked on three vertical dotted and it has the following features 
1. Copy link
2. Reply
3. Share
4. Add to bookmark.
 The number 1 feature is working ok, the Second one gives the option to reblog while it is for *Reply*.
The third one is Share but it works as *Reply* and the 4th one is working as *Share*.

**To Reproduce**
1. Go to 'Profile page'
2. Click on 'Three vertical dotted just right sides of your post'
3. Try to use the available functions

**Expected behavior**

**Screenshots or Video**
![img_e6415](https://user-images.githubusercontent.com/36129744/52951834-dbffaf80-33a8-11e9-94a2-8322725fd923.JPG)

**Smartphone (please complete the following information):**
 - Device: [ iPhone6]
 - OS: [e.g. iOS 12
 

**Additional context**

**Comment by ue** [comment]
Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link:
https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you. @face2face-utopian
