### ISSUE TITLE
[eSteem mobile ios] Not accepting suggested tag.

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#602]
**Describe the bug**
In the editor section, i was trying to choose keypad suggested categories tag such as Photography but when i clicked on suggested tag the app got only two letters *Ph*.
However if type full category tag and don't choose from suggestion then it is getting properly. 

**To Reproduce**
1. Go to the editor section of esteem mobile ios latest version.
2. Type some letters of the tag such as photography (Which you use frequently)
3. If you see the suggested tag according to you then tap on that.

**Expected behavior**
If any user select suggested or already used tag from keypad suggestion then this app should accept all characters.  
**Screenshots or Video**
https://youtu.be/QaNv15EbkeQ

**Smartphone (please complete the following information):**
 - Device: [ iPhone6]
 - OS: [ iOS12]
 - Version [2]

**Additional context**

**Comment by ue** [comment]
removed suggested for ios.
