### ISSUE TITLE
[eSteem mobile ios] Push notification not working

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#603]
Dear Team,
               In latest version of iOS released the Push notification is not working. Using this app i created a post but did not get any notification of upvotes and comments as i got in my android mobile.

Push notification is enabled in setting section
Device iPhone 6
iOS 12

**Comment by feruzm** [comment]
Can you check it again? I have changed some settings on server side.

**Comment by face2face-utopian** [comment]
Thanks!
Now it is working.
