### ISSUE TITLE
[eSteem mobile 2 iOS] Need to close and re-launh the app to view updated upvoter numbers & Values

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#609]
**Describe the bug**
I was getting multiple upvoting notifications for my recent post and thought to launch the app to see them but when i launch the app i saw that there is only one upvote. I tried to pull down to refresh the page but it gave no result. 

**To Reproduce**
1. Create a new post.
2. Check that it is visible in the profile page.
3. minimize the app pressing the home button of iphone.
4. Wait for a moment and maximize the app using double tapping on home button.
5. See the error. You can try to refresh the page by pulling down.

**Expected behavior**
If i am getting proper notifications of upvote then the upvoter numbers and its upvote value should be updated on post simultaneously.
**Screenshots or Video**

**Smartphone (please complete the following information):**
 - Device: [ iPhone6]
 - OS: [e.g. iOS 12]
 - Version 

**Additional context**

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
