### ISSUE TITLE
[eSteem mobile v2 iOS] After submiting post not displays on user profile page

### ISSUE THREAD

**Issue by face2face-utopian** [esteemapp/esteem-mobile#610]
**Describe the bug**
After successful submission of my last post using eSteem mobile v2 iOS release visited my profile page where the new post was unavailable. I tried to refresh the page but no avail and finally close the app and re-launch it then post displays properly in the profile page.

**To Reproduce**
1. Create a new post using eSteem mobile v2 ios release
2. Click on publish.
3. Visit your profile page.
4. You can see the error.
**Expected behavior**
I had expected that just after submitting my new post should appears on my profile page without any delay.

**Screenshots or Video**

**Smartphone (please complete the following information):**
 - Device: [ iPhone6]
 - OS: [e.g. iOS12]
 - Version []

**Additional context**

**Comment by ue** [comment]
Thanx for feedback. Fixed.
