### ISSUE TITLE
Putting a YouTube link into MarkDown Link Syntax Still Shows Video

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#621]
#### Expected behavior

I expect the app Post_Preview to display a link instead of video after parsing YouTube link into a Markdown Link Syntax e.g `[YouTube Link](https://www.youtube.com/watch?v=41-KcNmZgrA)`

#### Actual behavior

Video is shown instead of a link.

#### How to reproduce

- Open app
- Open Editor
- Incorporate a YouTube link into MarkDown link syntax
- Check the post preview

***
* App version: v2.0.8
* Operating system: Android 8.0.1
***

#### Recording Of The Bug
<img src="https://i.ibb.co/F7gX72v/G-20190221-1115272.gif" alt="G-20190221-1115272" border="0">

**Comment by horpeyloaded** [comment]
https://github.com/esteemapp/esteem-mobile/issues/577

**Comment by ue** [comment]
![Screen Shot 2019-03-31 at 13 31 21](https://user-images.githubusercontent.com/9980498/55287977-4e58ac00-53b9-11e9-908a-c8f0e9d2bd28.png)

Could you please test and close if it okay.

Android Apk Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/beta_testers
IOS Ipa Download link: https://install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/beta_testers

Thank you.

**Comment by horpeyloaded** [comment]
No updated app for testers

Latest; Version 2.0.9 (1246)
Mar 26, 2019
