### ISSUE TITLE
Estimated Wallet Value Is Not Correct

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#625]
#### Expected behavior

I expect to be shown correct estimated account value.

**This is the eStimated value shown by eSteem v2**

<img src="https://i.ibb.co/wcCPt5b/Screenshot-2019-02-23-11-05-06.png" alt="Screenshot-2019-02-23-11-05-06" border="0">

#### Actual behavior

The estimated value is incorrect.

**This is the eStimated value shown by Steemit and other UI**

<img src="https://i.ibb.co/VQXtmVX/Screenshot-2019-02-23-11-04-56.png" alt="Screenshot-2019-02-23-11-04-56" border="0">

#### Caused
The tokens (Steem or SBD) transferred to **Savings** are not added to the Wallet calculation. 

The estimated wallet value should be; (( SP + Steem + Savings Steem) * Value of Steem) + (( SBD + Savings SBD) * Value of SBD)) = Estimated account value.

#### How to reproduce

- Open app & Login
- Goto Wallet Tab
- Check the estimated wallet value
- Compare it with Steemit and other UI

***
* App version: v2.0.8
* Operating system: Android 8.0.1
***

#### Recording Of The Bug
- - -

**Comment by mistikk** [comment]
This issue has been solved in our latest update, can you check from below links and if it is okay for you or you have any feedback please let me know, thank you :) @horpeyloaded

iOS : install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/internal
Android : install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/internal

**Comment by horpeyloaded** [comment]
eSteem has stopped error

**Comment by horpeyloaded** [comment]
Fixed 👍 @mistikk
