### ISSUE TITLE
Navigating to second logged in account wallet makes app restart  

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#631]
#### Expected behavior

I expect to see the second logged in account wallet details.

#### Actual behavior

App restarts when I navigate to Wallet  on the second logged in account.

#### How to reproduce

- Open app & Login
- Login second account
- Make the second account active
- Goto Wallet Tab

***
* App version: v2.0.8
* Operating system: Android 8.0.1
***

#### Recording Of The Bug
<img src="https://i.ibb.co/HBG5r4M/G-20190225-2319412.gif" alt="G-20190225-2319412" border="0">

**Comment by mistikk** [comment]
This issue has been solved in our latest update, can you check from below links and if it is okay for you or you have any feedback please let me know, thank you :) @horpeyloaded 

iOS : install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/internal
Android : install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/internal
