### ISSUE TITLE
Images not shown fully in Post Preview Screen

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#636]
##### Check the legacy preview
<img src="https://i.ibb.co/cYsT4mx/Screenshot-20190226-140948.png" alt="Screenshot-20190226-140948" border="0">

##### v2 preview
<img src="https://i.ibb.co/sQYhYjf/Screenshot-20190226-140926.png" alt="Screenshot-20190226-140926" border="0">

**Comment by ue** [comment]
@horpeyloaded what is the post url?

**Comment by horpeyloaded** [comment]
I can't get the post URL @ue
