### ISSUE TITLE
Opening links with esteem mobile doesn't work when the app is open or running in the background.

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#683]
**Describe the bug**
In the latest update of the app, I can now open links from Steemit, busy and steempeak with the app. I tried this out and it didn't work when the app was open. But, when I closed the app, the function worked. 

**To Reproduce**
Ensure you have launched the app, and it is running in the background
1. Click on a steemit, busy, or steempeak link
2. Select option to open with Esteem
3. See error (The app launches, but the page of the link doesn't open)

**Expected behavior**
I expected that even though the app was open, when I open a link with it, the link should open. 

**Screenshots or Video**
https://www.youtube.com/watch?v=U9GiUDPizmg

**Test Environment**
 - Device: Redmi Note 5 pro
 - OS: Android 8.1
 - Software version: Esteem mobile 2.0.9

**Additional context**
- Is there a way to bypass boot screen?
- Please make pincode security optional.

**Comment by mistikk** [comment]
it is same issue with #590
