### ISSUE TITLE
App crashed when I was replying a post

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#684]
The eSteem announcement post and my typed texts wiped. I suggested comment should hold texts/save to local until it is submitted but it's not implemented.

**Comment by ue** [comment]
@feruzm @horpeyloaded I could not repreduce this issue

**Comment by horpeyloaded** [comment]
The app crashes/freezes when you use the app for up to 10mins @ue

**Comment by ue** [comment]
@horpeyloaded can you record a video for that
