### ISSUE TITLE
Searched results not visible in night mode [Visual error]

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#693]
#### Expected behavior

I expected the search results to be visible to the users.

#### Actual behavior

The search results display in gray color which is not clearly visible to users.

#### How to reproduce

- Open app
- Login
- input words in the search text box

***
* App version: v2.0.9
* Operating system: Android 8.0.1
***

#### Recording Of The Bug

<img src="https://i.ibb.co/jr3Tz9S/G-20190317-0712092.gif" alt="G-20190317-0712092" border="0">

**Comment by mistikk** [comment]
did you test last version @horpeyloaded it is working as expected for me. 
![image](https://user-images.githubusercontent.com/8211075/54739332-c14b7100-4bc8-11e9-9aab-6cf9e4ba5af8.png)

**Comment by horpeyloaded** [comment]
Yeah, I just re-tested it with the latest version still the same

<img src="https://i.ibb.co/NZ328f3/Screenshot-20190321-092501.png" alt="Screenshot-20190321-092501" border="0">

**Comment by horpeyloaded** [comment]
Yeah, I just re-tested it with the latest version still the same

<img src="https://i.ibb.co/NZ328f3/Screenshot-20190321-092501.png" alt="Screenshot-20190321-092501" border="0">

**Comment by horpeyloaded** [comment]
Yeah, I just re-tested it with the latest version still the same

<img src="https://i.ibb.co/NZ328f3/Screenshot-20190321-092501.png" alt="Screenshot-20190321-092501" border="0">

**Comment by mistikk** [comment]
This issue has been solved in our latest update, can you check from below links and if it is okay for you or you have any feedback please let me know, thank you :) @horpeyloaded 

iOS : install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/internal
Android : install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/internal
