### ISSUE TITLE
Clicking on Transferred notification opens user's feed without bottom menus

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#694]
#### Expected behavior

I expected the Transferred notification to redirect users to the wallet with details about the transfer.

#### Actual behavior

It redirects users to feed without bottom menus.

#### How to reproduce

- Open app
- Login
- Tab the notification icon
- Click on any notified `transfer`.

***
* App version: v2.0.9
* Operating system: Android 8.0.1
***

#### Recording Of The Bug

https://i.ibb.co/NpLF75T/G-20190317-0746572.gif

<img src="https://i.ibb.co/NpLF75T/G-20190317-0746572.gif" alt="G-20190317-0746572" border="0">

**Comment by ue** [comment]
not its go direct to wallet screen before its goes crush. So now expected behavior it should open wallet tab? @feruzm

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
