### ISSUE TITLE
When I searched for words instead of a steem user, when I click on the post result, it doesn't load. 

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#699]
**Describe the bug**
I searched for some words using the search bar on the app. After the results came up, I clicked on it to read a post from the search results. It opened, but, the content refused to load. My internet connection wasn't the issue because I searched for a user profile and clicked on a search result and the profile opened properly. 

**To Reproduce**
After doing all the necessary steps to get into the app; 
1. Click on the search icon located at the top right of the app.
2. Type in a word in the search bar 
3. Click on any of the search results
4. See error. (Page opens, but, content doesn't load).

**Expected behavior**
I expected that if I clicked on a search result (which definitely is an article), the content would load for me to be able to read it. 

**Screenshots or Video**
https://youtu.be/zlTpb-9WTVE

**Test Environment**
 - Device: Redmi Note 5 pro
 - OS: Android 8.1
 - Software version: Esteem mobile 2.0.9

**Comment by ue** [comment]
@feruzm  Fixed for IOS not published for Andorid

**Comment by mistikk** [comment]
This issue has been solved in our latest update, can you check from below links and if it is okay for you or you have any feedback please let me know, thank you :) @HarryHeights 

iOS : install.appcenter.ms/orgs/esteem.app/apps/esteem-1/distribution_groups/internal
Android : install.appcenter.ms/orgs/esteem.app/apps/esteem/distribution_groups/internal

**Comment by HarryHeights** [comment]
lemme check it out @mistikk

**Comment by HarryHeights** [comment]
The issue has been fixed.
