### ISSUE TITLE
Search on the the list of people I'm following doesn't work. It is unresponsive.

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#702]
**Describe the bug**
When I typed in some letters which are supposed to be part of usernames of people I'm following on steemit, the search is unresponsive. It is as though I'm not searching for anything. 

**To Reproduce**
1. Go to your profile
2. Click on your "following" 
3. Click on the search icon
4. Try to search for a username
5. See error. 

**Expected behavior**
I expected that as soon as I type in some letters, usernames that contain any of the letters I type would begin to show. I expected this behaviour because, that's what happens when I search on the list of my followers. 

**Screenshots or Video**
https://youtu.be/BcCIPsXUJCk

**Test Environment**
 - Device: Redmi Note 5 Pro
 - OS: Android 8.1
 - Software version: Esteem mobile 2.0.9

**Comment by ue** [comment]
Fixed
