### ISSUE TITLE
[FR] Some improvements for the mute feature. 

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#704]
This feature request stems from an issue with the mute function on the app. 

Firstly, I expected that when I mute a user, the option that should be visible when I check that menu option again should be `unmute`.  But, right now, I still see the option to mute the user. This made me think that the mute function didn't work. I was almost reporting the issue as a bug until I decided to check my list of muted users on steemit and I found out that it actually worked.  Now it's a cool thing that I can mute a user directly from esteem mobile. What isn't cool is the fact that I can't unmute a user. 
Another thing that would be nice to is if there was a list of mute users on the app. It would be great to be able to keep track of muted users on the app. 

Here are my suggestions in details

1. Display a toast notification to indicate that I muted a user.
2. When I mute a user, let there be an icon on the profile to show that that user has been muted.
3. When I access the option menu to mute a user, when the user is already muted, it should be unmute instead. This means that I'm suggesting the ability to unmute a user. 
4. Create a page on the app to access list of muted users.

**Comment by ue** [comment]
Fixed
