### ISSUE TITLE
Can't comment on post If esteem is accessed through post link on discord

### ISSUE THREAD

**Issue by cckole** [esteemapp/esteem-mobile#711]
### Actual behaviour

When I clicked a post link on discord and opened with esteem app, I tried to comment on the post by clicking the reply icon but it keeps bouncing back. 

### Expected behaviour

I expected to be able to comment without the comment icon bouncing back automatically without control.

### How to reproduce 

- Open discord messaging app

- locate any post link and click on it

- open the link with esteem app

- scroll down and click on a reply icon to make a comment either on the main post or the comments already made on the post.

- You will not be allowed to comment. It will open the comment box and bounce back. That's the error.

### The recorded bug

https://youtu.be/76JDQkQ3ecI

***Device used*** : Techno Spark
***Operating system*** : Android 7.0

**Comment by mistikk** [comment]
fixed
