### ISSUE TITLE
No Action is carried out when you click on the Comment Icon of Post cover

### ISSUE THREAD

**Issue by tony-duke** [esteemapp/esteem-mobile#715]
On your feed section where where you view different posts, the comment icon which is meant to take you to the comment section of that post doesn't perform any action when you click on it. 

I used a an Android 7.0 on the latest esteemapp update.

**Comment by mistikk** [comment]
@tony-duke thanks for feedback,  can you share screenshot or video for more information?

**Comment by tony-duke** [comment]
https://youtu.be/tB6a834-TXI

From the video you will see the that when you click on the comment icon, it highlights but nothing happens.

**Comment by mistikk** [comment]
@tony-duke thank you, we will fix that :)

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
