### ISSUE TITLE
Bullet shortcut places cursor at the back of the first letter in the editor

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#718]
#### Expected behavior

I expected all my words should be typed forward in the editor. 

#### Actual behavior

The first letter was typed appropriately, and the rest went back to the first letter.
quoine
#### How to reproduce

- Open app
- Login
- Tab the Bullet Symbol in the editors shortcut
- Type words

***
* App version: v2.0.9
* Operating system: Android 8.0.1
***

#### Recording Of The Bug

<img src="https://i.ibb.co/8zn3pk7/G-20190323-0648422.gif" alt="G-20190323-0648422" border="0">

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
