### ISSUE TITLE
Deleting Bullet symbol crashes app

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#719]
#### Expected behavior

I expected the app to main its state not crashed.

#### Actual behavior

The app crashed.

#### How to reproduce

- Open app
- Login
- Tab the Bullet Symbol in the editors shortcut
- Delete bullet

***
* App version: v2.0.9
* Operating system: Android 8.0.1
***

#### Recording Of The Bug

<img src="https://i.ibb.co/xFmnB1x/G-20190323-0652034.gif" alt="G-20190323-0652034" border="0">

**Comment by HarryHeights** [comment]
Already reported
