### ISSUE TITLE
I was able to bypass the app's security system, but the app eventually crashed.

### ISSUE THREAD

**Issue by HarryHeights** [esteemapp/esteem-mobile#721]
**Describe the bug**
Esteem mobile requires an internet connection for it to launch properly. Without an internet connection, the app won't start up. I'd always get the `no internet connection` message, and the app would just be stuck on the boot screen until I turn on my internet connection or exit the app. The security system also works with an internet connection.  However, I discovered that there was a way to beat this system. It took some level of precision but I could do it anytime I wanted. Kudos, to the dev team though. Although I was able to bypass the lock system, the security of my account wasn't compromised. I got into the app and my account wasn't even loaded. However, I could change some settings. I don't know, but, someone with a higher level of expertise might find a way to get into my account, but, I can't say for certain. 
Well, after I got into the app, and navigated around some menus, the app crashed. It took about 1-3 minutes for the app to crash.  

**To Reproduce**

Like I described above, it takes a certain level of precision to bypass the security system. 

- The first thing to do is; access the app with your internet connection active. 
- When the app is starting up, there's a small space inbetween where I can access the app. (Like as though the app was open). In that space of time, disable your internet connection. 
- Since the security system of the app works with internet, turning of the internet means the protocol won't come up.
- So, now you have access to the app, but, nothing would work, and I expected that behaviour. 
- But after some time navigating through menus on the app that can be accessed and trying to perform some actions, the app would crash. I don't know if it is a failsafe system. 

*Please you have to be on the app for at least 3 minutes for the crash to occur*

**Expected behavior**

I was unable to use the app, even though I had bypassed the security system. But, a crash wasn't expected. I expected that the app would be redundant until I close it manually. 

**Screenshots or Video**
https://youtu.be/oDJuV_C_8lc

**Test Environment**
 - Device: Redmi Note 5 Pro
 - OS: Android 8.1
 - Software version: Esteem mobile v2.0.9

**Logcat**

``` java.lang.ClassCastException: Value for title cannot be cast from ReadableNativeMap to String
	at com.facebook.react.bridge.ReadableNativeMap.checkInstance(ReadableNativeMap.java:148)
	at com.facebook.react.bridge.ReadableNativeMap.getNullableValue(ReadableNativeMap.java:140)
	at com.facebook.react.bridge.ReadableNativeMap.getString(ReadableNativeMap.java:190)
	at com.facebook.react.modules.dialog.DialogModule.showAlert(DialogModule.java:232)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
	at android.os.Looper.loop(Looper.java:176)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
	at java.lang.Thread.run(Thread.java:764)
```

**Additional context**
I have often talked about scrapping the boot screen. It could be there after the first launch, but at subsequent times, it would be great to just get through to the security system of the app. The security system also, is a thing that needs to be optional.

**Comment by ue** [comment]
The internet connectivity feature temporarily disabled. This neither a hack neither an unexpected behavior your account already dos not loaded as I saw the record. Also our pincode system not working with internet or something when you logged in successfully the app will ask your pincode until that time you can not share any item of that. if you share somthing from your account with out pincode in first opening that will be a hack. Also the hack not kind ot thing.

**Comment by HarryHeights** [comment]
Oh okay

**Comment by HarryHeights** [comment]
The crash was expected too?
