### ISSUE TITLE
Author and Benefactor rewards shows only SBD payouts in wallet

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#727]
#### Expected behavior

I expected both the Author and Benefactor rewards should be displayed in details i.e shows the number of SP, SBD and Steem like the screenshot below. 

<img src="https://i.ibb.co/QQFytjJ/Screenshot-2019-03-25-13-01-56.png" alt="Screenshot-2019-03-25-13-01-56" border="0">

#### Actual behavior

It shows only the SBD rewards.

<img src="https://i.ibb.co/vYwVS6r/Screenshot-2019-03-25-13-07-15.png" alt="Screenshot-2019-03-25-13-07-15" border="0">

#### How to reproduce

- Open app
- Login
- Tab the Wallet bar
- Check your history of the Author and Benefactor payouts.

***
* App version: v2.0.9
* Operating system: Android 8.0.1
***

#### Recording Of The Bug

- -

**Comment by mistikk** [comment]
@horpeyloaded it is fixed can you check with latest store version
