### ISSUE TITLE
Vote value and number of voters are not displayed on comments

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#733]
#### Expected behavior

I expected number of voters and vote value should be displayed on comments like the screenshot below.

<img src="https://i.ibb.co/nRkBzsg/Screenshot-2019-03-28-21-15-06.png" alt="Screenshot-2019-03-28-21-15-06" border="0">

#### Actual behavior

It remains at zero 
 
<img src="https://i.ibb.co/1r87HFf/Screenshot-2019-03-28-21-15-16.png" alt="Screenshot-2019-03-28-21-15-16" border="0">

#### How to reproduce

- Open app
- Open a post with comments voted

***
* App version: v2.0.9
* Operating system: Android 8.0.1 
***

**Comment by mistikk** [comment]
Can you share post link? @horpeyloaded

**Comment by horpeyloaded** [comment]
@mistikk 

https://steemit.com/motivation/@horpey/beyourself-sagewords31-k3837uixm1
