### ISSUE TITLE
Suggestion to add payout option to settings

### ISSUE THREAD

**Issue by dayjee111** [esteemapp/esteem-mobile#734]
I was unable to adjust my payout settings to 100% power up because I did not find the option in the settings or below the post before submission. I hope the team will fix this soon.

**Comment by horpeyloaded** [comment]
I'm sure you still using the Legacy version. Download eSteem v2 from app/play store.

**Comment by umair1209** [comment]
Already present on the newest version.

**Comment by mistikk** [comment]
It is already implemented on v2, please check from app markets @dayjee111
