### ISSUE TITLE
Visiting a steem link through app opens the post randomly

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#736]
#### Expected behavior

I was expecting not to see random pop up of a link opened with the app.

#### Actual behavior

It pops up the post visited through steem link randomly.

#### How to reproduce

- Don't run app
- Open a link through eSteem app - [Link Here](https://steemit.com/agfacademy/@dfacademy/gxpruda-dfa-drills-inspired-by-agfa-day-25)
- Navigate out of the link
- See the visited post pop up randomly
- or After navigating out of the visited link, tab on Vote list of any post... you will  notice the pop up too.

***
* App version: v2.0.9
* Operating system: Android 8.0.1
***

#### Recording Of The Bug
<https://i.ibb.co/q9qn7xr/G-20190329-2031008.gif>
<img src="https://i.ibb.co/q9qn7xr/G-20190329-2031008.gif" alt="G-20190329-2031008" border="0">

**Comment by ue** [comment]
@mistikk  I guess this issue related with notification #847

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
