### ISSUE TITLE
[BUG] The reply box force closes before typing 

### ISSUE THREAD

**Issue by dongentle2** [esteemapp/esteem-mobile#741]
**Describe the bug**
I had issues replying to any post. Whenever I click on the reply button, the reply box force closes before I can successfully type my full reply. 

**To Reproduce**
1. Go to a post from the application 
2. Click on reply
3. Start typing 

**Expected behavior**
I expected the reply box to stay so that i can complete my typing and reply before force closing 

**Screenshots or Video**
https://youtu.be/iVc7OnHNJc0
Above is the video link. 
**Smartphone (please complete the following information):**
 - Device: [Infinix hot 5]
 - OS: [Android 7.0]
 - Software Version: Esteem mobile v2.0.9

**Comment by mistikk** [comment]
@dongentle2 can you retest with last release?

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
