### ISSUE TITLE
Visiting a user from the upvote page redirects to a random post

### ISSUE THREAD

**Issue by dongentle2** [esteemapp/esteem-mobile#742]
**Describe the bug**
I tried visiting a user from the upvote list of a post  but Instead of arriving at the user's page,  I was redirected to a random post few seconds after the user's page attempted to load. 

**To Reproduce**
1. Go to a post from the application 
2. Click on the upvote list
3. Click on your desired user

**Expected behavior**
I expected the application to take me to the user's page that I clicked but I was redirected to a different post. 

**Screenshots or Video**
https://youtu.be/W7uyQXNbLSY
Above is the video link. 

**Smartphone (please complete the following information):**
 - Device: [Infinix hot 5]
 - OS: [Android 7.0]
 - Software Version: Esteem mobile v2.0.9

**Comment by horpeyloaded** [comment]
Already reported

**Comment by dongentle2** [comment]
I guess you are referring to issue #695.... That issue and mine are two different issues and yours was marked fixed while mine is still not fixed.

**Comment by horpeyloaded** [comment]
It's the same… I'm not a mere bug reporter here. It’s fixed but app is not released to the public.

**Comment by dongentle2** [comment]
Thanks for the feedback... I'm looking forward to enjoying the feature when it finally comes to the public.
