### ISSUE TITLE
eSteem v2 - clicking on upload image doesn't work

### ISSUE THREAD

**Issue by chrisbarth01** [esteemapp/esteem-mobile#743]
#### Expected behavior

I expected it to add the selected image to the post that was to be published.

#### Actual behavior

It redirects users back to the create post page without adding the selected image.

#### How to reproduce

- Open app
- Login
- Click on the '+' to make post
- Select an image for the post

---

#### Device
- App version: v2.0.9
- Operating system: Android 6.0

---

#### Video
https://youtu.be/6ozpxNwU8L4

**Comment by ue** [comment]
Which device are you using? @chrisbarth01

**Comment by chrisbarth01** [comment]
Gionee f100s @ue

**Comment by ue** [comment]
@chrisbarth01 did you tested with latest build? Are you still see this issue?

**Comment by chrisbarth01** [comment]
I used version 2.0.9 and I'm still having the issue

**Comment by horpeyloaded** [comment]
Download the latest version from playstore, it's fixed.

**Comment by chrisbarth01** [comment]
Ok

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
