### ISSUE TITLE
[BUG] app collapsed when I clicked on the camera button and opt out by pressing the phone back button.

### ISSUE THREAD

**Issue by darewealth** [esteemapp/esteem-mobile#746]
### Describe the bug
when I clicked on the camera icon and decided to opt out by pressing the phone back button without going further, the app collapses.

### Steps to reproduce the behavior:
1. open the app 
2. Click on the plus sign below the screen to reveal the available features  
3. Click on the camera icon
4. Click the phone back button to go back to the app
5. The app will misbehave and collapse.

### Expected behavior
I expected to be taken back to the app when I pressed the back button, and not for the app to collapse.

### Screenshots or Video
https://www.youtube.com/watch?v=hCvg_aM6Hyw&feature=youtu.be

**Smartphone (please complete the following information):**
 - Device:  [ itel ]

 - Version [Android 6.1]

- App version [2.0.9]

**Comment by ue** [comment]
@darewealth Fixed
