### ISSUE TITLE
[BUG] Taking photo and clicking the white mark makes the app to collapse. 

### ISSUE THREAD

**Issue by darewealth** [esteemapp/esteem-mobile#747]
### Describe the bug
I clicked on the video icon and it took me to a page to take a picture. After snapping, i clicked the white check mark with the intention that it would be uploaded to the editor, but the app misbehaves and collapsed

 ### To Reproduce

### Steps to reproduce the behavior:

1. Open the app
2. Click on the plus sign below the screen
3. Click on the video sign
4. take a picture and click on the white mark 
5. The app will misbehave and collapse

### Expected behavior
After taking a picture and clicking the white mark sign, I expected the pictures link to be uploaded into the app editor

### Screenshots or Video
https://www.youtube.com/watch?v=zFsZMqd20xo&feature=youtu.be

### Smartphone (please complete the following information)
 - Device: [Itel]
 
 - Version [6.1]

- App version [2.0.9]

**Comment by mistikk** [comment]
It is not implemented yet, we will add this feature on next release, you can follow to his issue #433
