### ISSUE TITLE
Esteem mobile app doesn't load any selected image 

### ISSUE THREAD

**Issue by chrisbarth01** [esteemapp/esteem-mobile#749]
**Expected behavior**
- I expected the image I select to successfully load without any issue

**Actual behavior**
- After clicking on an Image, it shows no signs of loading; image doesn't load

**How to reproduce**
- Download and install the latest release of Esteem application.
- Launch the application 
- Click on the "+" icon and select the post(write) icon
- Click on the image icon at the down right corner
- Click "open gallery"
- Select any image
- It returns back without loading the image; error

---

- App version: 2.0.9
- Phone name: Gionee f100s 
- Operating system: android version 6.0

---

**Recording of the bug**
- https://youtu.be/djum7w0FAf4

**Comment by horpeyloaded** [comment]
This is not a bug 🐛… It shows check the top right corner.

**Comment by horpeyloaded** [comment]
https://github.com/esteemapp/esteem-mobile/issues/630

**Comment by chrisbarth01** [comment]
Hello @horpeyloaded, I believe I had complained this issue earlier to you on the eSteem telegram group. When I select an image, there is no sort of loading at the top right corner. Not even on any part of the screen. Even if I left the device for hours, nothing would load. Due to this error, I used an older version of the app to make posts and use the newer version to do other things. If you look at the video I made, you can see how obvious it is that I'm using two different eSteem applications.

**Comment by chrisbarth01** [comment]
@horpeyloaded, even another person has complained about an issue relating to mine on https://steemit.com/utopian-io/@darewealth/bug-app-collapsed-when-i-clicked-on-the-camera-button-and-opt-out-by-pressing-the-phone-back-button

**Comment by horpeyloaded** [comment]
I see 👍

**Comment by chrisbarth01** [comment]
So what will be done about it @horpeyloaded

**Comment by feruzm** [comment]
@chrisbarth01 We will look into this, thank you! Expect update early next week!

**Comment by mistikk** [comment]
fixed
