### ISSUE TITLE
eSteem app version 2.0.9; Link cannot be added (to a previously published post)  successfully 

### ISSUE THREAD

**Issue by chrisbarth01** [esteemapp/esteem-mobile#754]
**Expected behavior**
- I expected the link I added to the edited post to be added without having any issues 

**Actual behavior**
-  Once I add a link and save the post, it's either that the link won't be added or that the link will be long even when I try shortening the link with the '[text here](link here)' code

**How to reproduce**
- Download and install the latest version of the eSteem application.
- Launch the application 
- Login/sign-in to your steemit account 
- Click on a post you made before 
- Click on the edit icon at the bottom of the post
- Try adding a link in the post using the '[text here](link here)' code
- Update the post
- Bug is then reproduced 

---

- App version: 2.0.9
- Device: Gionee f100s 
- Operating system: android version 6.0

---

**Recording of the bug**
- https://youtu.be/GWmuPsancWU

**Comment by mistikk** [comment]
@chrisbarth01 can you share this link for testing

**Comment by chrisbarth01** [comment]
Any link I edited ended up the same.

**Comment by mistikk** [comment]
alright I tested it is fixed. Just wait for next release :)

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
