### ISSUE TITLE
[BUG] [Esteem-Mobile V 2.0.9] Automatically  Space Remove from text  when i paste the text Data in Esteem  Mobile Application 

### ISSUE THREAD

**Issue by XAMIR555** [esteemapp/esteem-mobile#760]
> #### Project Information
* Repository    : https://github.com/esteemapp/esteem-mobile/releases
* Project Name  :  Esteem-Mobile
* Publisher     :   feruzm

#### Expected behavior

I Expected that when I paste the text data in   Esteem-Mobile application  the  spacing should not be removed from the original text 
 
#### Actual behavior

Automatically  Spacing  Remove from the text  when I paste the text Data in Esteem  Mobile Application  you can see in bug video properly 

#### How to reproduce
* [Download ](https://github.com/esteemapp/esteem-mobile/releases)the latest version and install it 
* open the application
* click on the plus button
* click on  pincle 
* Copy any text data
*  paste in Application 
* Note the Bug
* Browser/App version:   V 2.0.9
* Operating system:  7.0  

#### Recording Of The Bug
https://youtu.be/dm-yOr649Kg
#### GitHub Account
https://github.com/XAMIR555

# Logcat
[logcat.txt](https://github.com/esteemapp/esteem-mobile/files/3100983/logcat.txt)

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
