### ISSUE TITLE
[BUG] eSteem Mobile v2.1.0, 1648 (Android) / Upvote a post and App crashed

### ISSUE THREAD

**Issue by louis88-steemit** [esteemapp/esteem-mobile#802]
**Describe the bug**
When using the latest Version of the eSteem Mobile App as a fresh installation from the App Store (esteem V2) the App is crashing when i make a Upvote. The Vote is happen but the App crashes after hitting the Upvote Button.

**To Reproduce**
1. Go to the App Store and download the latest Version of eSteem Mobile App. (Delete previous Version if you have installed it)
2. Enter your Account Information and Login In to your Account
3. Go to a Post you Like and simple hit the Upvote Button
4. The App is crashed and have to open again.

**Expected behavior**
I expected the app not to crash after I did an upvote in the app. 

**Screenshots or Video**

![dQPVtip](https://user-images.githubusercontent.com/35930080/57449424-22ec9b00-725c-11e9-861d-73e36455b94c.gif)

https://i.imgur.com/dQPVtip.gif

**Smartphone (please complete the following information):**
 - Device: Huawai Mate 10 Pro
 - OS: Android
 - Version Latest Version 9 (with latest Security Patch from April 1st 19)

**Additional context**
The App Crashes also when:
- Reply to a Post
- Reblog a Post -> https://github.com/esteemapp/esteem-mobile/issues/801

**Comment by mistikk** [comment]
@louis88-steemit  it is fixed, can you test again?

**Comment by louis88-steemit** [comment]
@mistikk just tested the upvote, reblog and reply. works fine!
