### ISSUE TITLE
Bug updating existing post

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#806]
I found one more issue. If I update an existing reply, some characters go missing. For every update I do, the characters go missing. Please check one of my previous replies. I'm unable to edit the reply and add the missing characters. If I do so, it again disappears.

I have seen this problem earlier when I try to update an already published post using esteem app. For every update I do, some content from the article will disappear.

**Comment by mistikk** [comment]
can you share screenshot @horpeyloaded

**Comment by ue** [comment]
@feruzm  could you please test it with our internal latest build I already fixed but needs to test.  if it's fine we can close this issue.
