### ISSUE TITLE
Wallet line contents bottom is hidden

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#808]
<img src="https://i.ibb.co/23xTXWm/Screenshot-2019-05-09-08-32-10.png" alt="Screenshot-2019-05-09-08-32-10" border="0">

**Comment by ue** [comment]
@horpeyloaded do you know the device?

**Comment by horpeyloaded** [comment]
Infinix Note 5

**Comment by mistikk** [comment]
fixed
