### ISSUE TITLE
Points not given as stipulated on the point page

### ISSUE THREAD

**Issue by cckole** [esteemapp/esteem-mobile#817]
### App info

Name: Esteem app
Version:
Github:

### Description

I noticed that points are not given accordingly on the esteem point page. As instructed on discord, I uninstalled esteem app,re installed and logged in but the 99+ points on the first log in does not reflect on the point page. More so, there's no point given on every post as I've posted two times without any point. I only get 0.25 points on every usage.

### Expected behavior

I expected to be given the desired points as stipulated on the point page. E.g, 100 points on first login, 15 points on each post and so on.

### Steps to reproduce the bug

If you've not installed the latest version of esteem, uninstall and re install.

- Log in through Steem connect with your steemit username and active key

- Click on the gift item icon beside the plus sign by the right side to check your point

- Also, post through the platform, you would notice that the points won't be given. Only 0.25 points will keep showing for you to claim.

### Images 

Below shows the image of the 0.25 points

![dv2xz4ceqb.png](https://img.esteem.ws/dv2xz4ceqb.png)

Images of the normal points that should be given

![yzfj4s73nx.png](https://img.esteem.ws/yzfj4s73nx.png)

![hjjhfuohde.png](https://img.esteem.ws/hjjhfuohde.png)

### Device used

Techno Spark K7

Android 7.0

**Comment by mistikk** [comment]
@cckole it is fixed, can you test again?

**Comment by cckole** [comment]
Though I didn't get the 100 points at first log in, the points are now given as stipulated. I posted and reblogged and got the right point. Now working fine..Thanks.

**Comment by feruzm** [comment]
@cckole We are looking into it. It should appear once we confirm what's causing it and fix the issue.

**Comment by cckole** [comment]
Alright. Thanks.

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
