### ISSUE TITLE
Appic post images do not display

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#819]
#### Expected behavior
Appic is an image sharing app so I was expecting photos share by users to be displayed.

#### Actual behavior

The app do not display Appic images when opened with the app.

#### How to reproduce

- Open eSteem mobile app
- Open an Appic [post](https://steemit.com/appics/@hungrypb/alpha-kw-8-appics-im-18558) 

***
* App version: v2.1.0
* Operating system: Android 8.0.1
***

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
