### ISSUE TITLE
Post didn't show up on esteem app after posting [BUG]

### ISSUE THREAD

**Issue by emmali73** [esteemapp/esteem-mobile#822]
**After publishing of the post, the post didn't show up on personal profile page and the photo wasn't shown too**

**To Reproduce**
1. Go to 'profile details page'
2. Click on 'posts'
3. Scroll down to 'blogs'

**Expected behavior**
Right after publishing, the post should be shown on the personal page right away. I went to other sites like busy.org, and partiko app, the post was shown right away but not on esteem app. Also I uploaded the photo to the post, but the photo didn't show up on the post that was seen on other 3rd party app(aka busy and partiko).

**Screenshots or Video**

**Smartphone (please complete the following information):**
 - Device: [Iphone 8+]
 - OS: [iOS12.2]
 - Version [12.2]

**Additional comments** 
I am uploading two photos to show the issue. One is a snapshot from Partiko, the other one is from esteem app. You can see the post on the snapshot from Partiko, but not on esteem. 

![WechatIMG1046](https://user-images.githubusercontent.com/33790347/57561801-00da4200-735c-11e9-99cb-0e6bcb93f8c1.jpeg)
![WechatIMG1048](https://user-images.githubusercontent.com/33790347/57561802-0172d880-735c-11e9-92e8-70b79523a427.jpeg)

**Comment by mistikk** [comment]
fixed
