### ISSUE TITLE
ESTEEMv2.1 Reward interface displays an error "Request failed with the status code 404"

### ISSUE THREAD

**Issue by realrufans** [esteemapp/esteem-mobile#825]
# Expected Behavior

To successfully load the page without error.

# Actual Behavior
It displays a 404 error

# HOW To Reproduce

- Launch app
- click on the reward button
- watch the error display

# Screenshots or Video
![MNML-May11-1159-1557572480464.gif](https://cdn.steemitimages.com/DQmbVMsf3eN2qSkU5dqfPzSFov5H61cpevX8kTCgX4gDGNc/MNML-May11-1159-1557572480464.gif)

# Device And Operating System

OS: Android 8.1
Version: Esteem mobile v2.1

**Comment by horpeyloaded** [comment]
That was due to network or connected server error, not a bug from the app. Check it now or better change your connected server to rpc.esteem.app

**Comment by realrufans** [comment]
@horpeyloaded still same error.

**Comment by horpeyloaded** [comment]
That's weird, I can't reproduce that here

**Comment by horpeyloaded** [comment]
kindly uninstall your app completely and install again. I can't reproduce it here.

**Comment by realrufans** [comment]
okay

**Comment by realrufans** [comment]
Worked
