### ISSUE TITLE
Youtube video shows as a link

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#826]
#### Expected behavior

I was expecting the post preview panel of the app to show Youtube video link as a video instead of link.

#### Actual behavior

It shows Youtube link as a mere hyper link. 

<img src="https://i.ibb.co/8X19bYS/Screenshot-2019-05-11-12-57-46.png" alt="Screenshot-2019-05-11-12-57-46" border="0">

#### How to reproduce

- Open eSteem mobile app
- Open a post that contains YouTube video e.g [link](https://steemit.com/nigeria/@dfacademy/football-coaching-academy-ball-walk-with-cones)
- 

***
* App version: v2.1.0
* Operating system: Android 8.0.1
***

#### Recording Of The Bug

--

**Comment by ue** [comment]
@mistikk can you please test with latest changed for this post

**Comment by mistikk** [comment]
it is fixed

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
