### ISSUE TITLE
Profile image thumbnail not shown

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#827]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots or Video**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ue** [comment]
@horpeyloaded  screenshot and description need

**Comment by horpeyloaded** [comment]
@ue earlier version of the app displayed user's profile template.
Description given in the image below

<img src="https://i.ibb.co/D1sGDvC/Screenshot-2019-05-19-23-51-45.png" alt="Screenshot-2019-05-19-23-51-45" border="0">

<img src="https://i.ibb.co/Zfg82Sz/Screenshot-2019-05-19-23-52-40.png" alt="Screenshot-2019-05-19-23-52-40" border="0">

**Comment by ue** [comment]
Fixed
