### ISSUE TITLE
[BUG][Esteem mobile v2.1]The app crashes if I click on Dark theme

### ISSUE THREAD

**Issue by 44asad** [esteemapp/esteem-mobile#834]
### Expected behavior
The application should not crash when I click on Dark Theme.

### Actual behavior
the application is crash when I click on Dark theme.

### How to reproduce:
* Download the app and open it
* Then login naw
* Click the menu icon.
* click on setting 

* Then click Dark theme
* 2-3 step
* see bug
### Recording Of The Bug:
https://youtu.be/wPwsVNmBGF8
### Test Environment:

Device:samsung J5
OS: Android 6.0.1
Version: Esteem mobile v2.1

### Logcat:

<pre><code>05-12 21:17:12.069 31285 31320 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-12 21:17:12.069 31285 31320 E AndroidRuntime: Process: app.esteem.mobile, PID: 31285
05-12 21:17:12.069 31285 31320 E AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException: lineNumber
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:122)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:126)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:180)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
05-12 21:17:12.069 31285 31320 E AndroidRuntime:   at java.lang.Thread.run(Thread.java:818)</code></pre>

**Comment by horpeyloaded** [comment]
The issue was fixed, kindly uninstall your app (eSteem v2) completely and install again. I can't reproduce it here.

**Comment by 44asad** [comment]
sir! new application  install. same problems

**Comment by 44asad** [comment]
@mistikk
today downloads  this last version  application but apps crash.my devices version  6.0.1
samsung j5.

**Comment by umair1209** [comment]
Dark theme is working perfectly for me.

**Comment by 44asad** [comment]
but not work my device samsung j5 version  6.0.1

**Comment by ue** [comment]
@44asad it could be related with another issue. Let's wait until new release.
