### ISSUE TITLE
[Esteem mobile v2.1]The app crashes if I click on date set

### ISSUE THREAD

**Issue by 44asad** [esteemapp/esteem-mobile#836]
### Expected behavior
The application should not crash when I click on date set.

### Actual behavior:
the application is crash when I click on date set.

### How to reproduce:
* Download the app and open it
* Then login naw
* Click naw "+" 
* select naw camera
* select image 
* and date select naw
* see bug
### Recording Of The Bug:

https://youtu.be/2bEDLc_qy-w

### Test Environment:

Device:samsung J5
OS: Android 6.0.1
Version: Esteem mobile v2.1
### logcat:
<pre><code>05-12 21:29:07.164  1262  1296 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
05-12 21:29:07.164  1262  1296 E AndroidRuntime: Process: app.esteem.mobile, PID: 1262
05-12 21:29:07.164  1262  1296 E AndroidRuntime: com.facebook.react.bridge.NoSuchKeyException: lineNumber
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:122)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at com.facebook.react.bridge.ReadableNativeMap.getValue(ReadableNativeMap.java:126)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at com.facebook.react.bridge.ReadableNativeMap.getInt(ReadableNativeMap.java:180)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at com.facebook.react.util.JSStackTrace.format(JSStackTrace.java:28)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at com.facebook.react.modules.core.ExceptionsManagerModule.reportSoftException(ExceptionsManagerModule.java:46)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:158)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
05-12 21:29:07.164  1262  1296 E AndroidRuntime:   at java.lang.Thread.run(Thread.java:818)</code></pre>

**Comment by mistikk** [comment]
@44asad did you test with last version?

**Comment by 44asad** [comment]
sir!this version 2.1.today downloads  this application

**Comment by umair1209** [comment]
Good catch.
I was also able to replicate the bug

**Comment by 44asad** [comment]
thanks you?  sir

**Comment by ue** [comment]
@mistikk please take a look.

**Comment by ue** [comment]
Fixed
