### ISSUE TITLE
The app crashes if I click on Recordig Camera

### ISSUE THREAD

**Issue by 44asad** [esteemapp/esteem-mobile#837]
### Expected behavior
The application should not error when I click on recording camera.

### Actual behavior:
the application is crash when I click on racording camera.

### How to reproduce:
* Download the app and open it
* Then login naw
* Click naw "+" 
* select naw recording camera
* see error
### Recording Of The Bug:
https://youtu.be/fW43TiuU0oM

### Test Environment:

Device:samsung J5
OS: Android 6.0.1
Version: Esteem mobile v2.1

**Comment by mistikk** [comment]
@44asad did you give cam permission?

**Comment by 44asad** [comment]
all allow ..but not work.plzzz  check it

**Comment by 44asad** [comment]
sir!

this a last version. Today downloads  this apps.
