### ISSUE TITLE
Great feedback from user on app

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#839]
eSteem has potential to become the go to app on iOS. Hopefully so very soon. Here are couple of little annoyances what in my humble opinion could be improved upon:

1. Text is sometimes way too small and having an option to increase it would be amazing

2. Mentioned it previously, but would like to emphasise it again - pin code for every time I open the app is very annoying.

3. Drop down menus such as Trending, Hot etc are too hard to hit and usually takes several tries to get where you want.

4. Under the first tab for Feed images on off toggle does not remember the choice and next time I open the app it’s back to default images on.

5. Sometimes trying to load new feed items doesn’t work. I can see newer posts in other apps and interfaces.

6. Search functionality does not seem to work at all as intended. Unable to find users or even posts I am actually searching for. 

And couple of things for the wish list:

1. Under notifications it shows the vote percentage however it would be amazing to see the value as well.

2. Vote strength slider is almost perfect, I like the extra decimals in value display however I’d like to see quick select options as well for instance 0%, 25%, 50, 75, 100

3. Wish app would be a little bit more responsive and faster overall

**Comment by ue** [comment]
couple of them already fixed for the other ones created new issue.
Thank you
