### ISSUE TITLE
[Suggestion] - Add "Re-blogged by ["username"]" Feature To Re-blogged Posts In Feed

### ISSUE THREAD

**Issue by erikah1** [esteemapp/esteem-mobile#843]
### Components
My suggestion is on the user's Feed page

### Proposal Description
I'd like to suggest a  "Re-blogged by ["username"]" feature to re-blogged posts in Feed. Right now re-blogged posts appear in my feed from users I don't follow just as posts from users I follow and there's no way I can figure out who has re-blogged it.  

### Mockups / Examples
![Screenshot_20190510-164605a](https://user-images.githubusercontent.com/47053627/57751794-8577e800-76ef-11e9-9260-1e04c35e9dc8.jpg)

Screenshot of my Feed page using eSteem Mobile V2.1.0, 1648. I'm not following @ jeezzle and the only reason I see this post in my feed is because someone I'm following has re-blogged it but  I can't check who it was because the feature is not added. 

![steemit-border](https://img.esteem.ws/av4tt0mlsg.png)

![Screenshot_20190510-164932a](https://user-images.githubusercontent.com/47053627/57751880-c8d25680-76ef-11e9-81f5-76281fdb0a98.jpg)

Screenshot of my Feed page using eSteem Mobile V1.6.0. It is clearly indicated who has re-blogged that particular post. 

![steemit-border](https://img.esteem.ws/av4tt0mlsg.png)

![esteem reblogged feature 1](https://user-images.githubusercontent.com/47053627/57751926-e8697f00-76ef-11e9-8db1-bae5d9bb7d69.jpg)

Screenshot of my Feed  page using  eSteem Surfer 2.0.7, also indicating who has re-blogged the post.

This would be really helpful because some users tent to re-blog a lot, which can be frustrating at times. Knowing who is re-blogging these posts can help me take action without having been forced to use another app.

**Comment by ue** [comment]
Thanx for your feedback. 
Fixed. Wait for our new release.
