### ISSUE TITLE
post reward shows $0 when see my own post from profile

### ISSUE THREAD

**Issue by razu788** [esteemapp/esteem-mobile#846]
**Describe the bug**
When seeing my own post from esteem app profile all recent post reward shows $0 though my post has some reward. For example one of my post has 0.33$ but when I check the post in profile there shows reward is $0. When I open the post from profile then I can see the reward. 

**To Reproduce**
1. Go to esteem app
2. Click on your profile picture to show sidebar
3. Click on the profile to see your post.
4. See all the recent post reward shows $0

**Expected behavior**
In the normal case, there should show the actual reward of every post.

**Screenshots or Video**
https://youtu.be/zJ8ESQFBXU8

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 4x
 - OS: Android 7.0
 - Version 1.6.0

**Comment by ue** [comment]
Hi @razu788 , thanks for the feedback but this is a first esteem application. Now most of user not using this at all. You can use our new eSteem v2 application. Just install from marketplace and enjoy.
