### ISSUE TITLE
Wrong Notifications[BUG]

### ISSUE THREAD

**Issue by tony-duke** [esteemapp/esteem-mobile#849]
**Describe the bug**
I keep getting notifications of other accounts that i am not signed into on my device. 

![Screenshot_20190517-063124_WhatsApp](https://user-images.githubusercontent.com/36610125/57905676-2ccf5900-786f-11e9-8e3e-1821a5a66f57.jpg)

**Additional context**
When i then click on those notifications, the app doesn't open, it keeps loading.

**Comment by horpeyloaded** [comment]
It’s a known issue

**Comment by horpeyloaded** [comment]
It’s fixed. Thanks for reporting
