### ISSUE TITLE
[BUG] The post was removed by user

### ISSUE THREAD

**Issue by peerzadaaabid** [esteemapp/esteem-mobile#850]
**Describe the bug**
Esteem displays following message while clicking on blog
"The post was removed by me"

**To Reproduce**
Steps to reproduce thebehaviourr:
1. Go to feed
2. Click on any post
3. Scroll down to the post

**Expectbehaviourviour**
As soon as I opened the blog, esteem displays  message that post was removed by me.

**Screenshots or Video**

https://youtu.be/V9a84bOsbKw

**Smartphone (please complete the following information):**
 
 - OS: [android 7.1.2 N2G47H]
 - Version [2.1.0,1648]

**Comment by ue** [comment]
revelant #831
