### ISSUE TITLE
Add refresh to Notification Tab

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#851]
Sometimes, it's not easy to view latest notification. Add reload option like that of Leaderboard

**Comment by ue** [comment]
there is already a refresh but it not visible. its doing every time on background

**Comment by ue** [comment]
@horpeyloaded  created 👍

**Comment by horpeyloaded** [comment]
I wanted to comment that it was not efficient as it's supposed to be. Thanks for implementing it 👍
