### ISSUE TITLE
[BUG]  esteem-mobile  v2.1.0  When a notification shows comments or votes and I try to open it, my post does not appear.

### ISSUE THREAD

**Issue by facebook-786** [esteemapp/esteem-mobile#863]
# Project Information

* Repository: https://github.com/esteemapp/esteem-mobile
* Project Name:  esteem-mobile

# Expected behavior

When any comments or vote appear in the notification, if I open these comments or votes, my personal post should be opened.

# Actual behavior

When a notification shows comments or votes and I try to open it, my post does not appear.

# How to reproduce

1-[Download ](https://github.com/esteemapp/esteem-mobile/releases)the application
2- When comments or votes appear in the notification, try opening it
3- You will see the message ( The Post was removed by You)
4- see bug 

* Browser/App version: v2.1.0 
* Operating system: 6.0.1
* Smartphone: Galaxy j7 

# Recording Of The Bug

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/50115498/57989766-9197d880-7a54-11e9-852e-387e3898a335.gif)

# My Github Account
https://github.com/facebook-786

**Comment by ue** [comment]
@facebook-786 we are working with that issue thanx for the report 💯 

#831 relevant.

**Comment by facebook-786** [comment]
welcome sir
