### ISSUE TITLE
Photo cannot gets upload captured by PicsArt or other camera rather than own camera and app gets restarted 

### ISSUE THREAD

**Issue by inzzzz** [esteemapp/esteem-mobile#864]
**Describe the bug**
When I want to upload a photo to my post I selected other app rather than my own phone's camera like PicsArt. I capture my photo but didn't able to upload it and when I try to upload it all gets restarted.

**To Reproduce**
1. Open the esteem app.
2. Click on write to post botton.
3. Then click on add to image botton.
4. Select PicsArt to capture photo.
5. Capture photo.
6. Click on ok botton in PicsArt.
7. After clicking on ok botton photo didn't upload and app gets restarted.
**Expected behavior**
When I wish to upload any photo to my post. I capture my photo with PicsArt app . After that I click on ok botton. The photo must upload and app did not gets restarted.
**Screenshots or Video**
https://youtu.be/z8i4Xl1AzsY

**Smartphone (please complete the following information):**
 - Device: Redmi 4
 - OS: 7.1.2
 - Version: 2.1.0

**Comment by ue** [comment]
Thanx for feedback. Dublicate issue.
