### ISSUE TITLE
[BUG][BUG] ] esteem-mobile v2.1.0 The active link displays as a wrong link! When server is set at rpc.esteem.app

### ISSUE THREAD

**Issue by peerzadaaabid** [esteemapp/esteem-mobile#865]
### Project Information
 Repository: https://github.com/esteemapp/esteem-mobile
Project Name: esteem-mobile

### Expected behaviour
The link should have been opened in a normal way.

### Actual behaviour
Here, when I clicked on the Repository link, esteem app display it as a wrong link and is not able to open it.

### How to reproduce
1-Download the application
2- Go to the Repository link
3- You will see the message ( oops wrong link)
4- see bug

Browser/App version: v2.1.0
Operating system: 7.1.2
Smartphone: redmi 5A

### Recording Of The Bug
https://youtu.be/KEPWrIo3qyo

### My Github Account
https://github.com/peerzadaaabid

**Comment by ue** [comment]
@peerzadaaabid we are working on them thanx for reporting 👍

**Comment by ue** [comment]
fixed
