### ISSUE TITLE
[BUG] esteem-mobile v2.1.0 The app displays error when server is set at steemd.previx.io

### ISSUE THREAD

**Issue by peerzadaaabid** [esteemapp/esteem-mobile#867]
### Project Information
 Repository: https://github.com/esteemapp/esteem-mobile
Project Name: esteem-mobile

### Expected behaviour
The app may have got successfully connected when I set the server at steemd.previx.io.
In order to check this is not network problem ,I set the server at api.steemit.com ,it got successfully connected.

### Actual behaviour
When I set the the server at steemd.previx.io, the app displays the message "connection failed".
### How to reproduce
1-Download the application
2- Go to the setting > server
3- Set server at steemd.previx.io
4- see bug (Connection failed message will be displayed)

Browser/App version: v2.1.0
Operating system: 7.1.2
Smartphone: redmi 5A

### Recording Of The Bug
https://youtu.be/xoqwTRg-Ygk

### My Github Account
https://github.com/peerzadaaabid

**Comment by horpeyloaded** [comment]
Close this... Meaning the server is not available
