### ISSUE TITLE
missing picture when posting

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#885]
Esteem app missing pictures from any content that i post ,,,i always need to edit my esteem content with previous version of esteemapp.
Can anyone help me to resolve this issue?
Why it miss pictures ?

**Comment by 4Ykw** [comment]
Not sure but verified this one today. If I cut the "![]()" bit part of it, it shows fine.

**Comment by ue** [comment]
not reproducible can you record a video @horpeyloaded
