### ISSUE TITLE
Editor bug

### ISSUE THREAD

**Issue by horpeyloaded** [esteemapp/esteem-mobile#887]
I made a post today. Few seconds before hitting the publish button, I uploaded an image to the post. After publishing the post, the image that I added few seconds before was not there.
Then I went to edit the post. I tried uploading the image over 3 times and submitted edits. It was still not happening. Then I uploaded again and then added few more additional words to the article. This time image was uploaded but some contents of the post were truncated at the bottom of the post. I have been experiencing this behavior for a long time.

https://cdn.discordapp.com/attachments/385448634197737484/580507554174599189/Screenshot_20190522-025515.png

**Comment by ue** [comment]
@horpeyloaded It have been tested til this day please re-check this issue if you see it again reopen. Thanks
