### ISSUE TITLE
[BUG] Opening of blog/post takes more time to open than expected!

### ISSUE THREAD

**Issue by peerzadaaabid** [esteemapp/esteem-mobile#888]
project Information

Repository: https://github.com/esteemapp/esteem-mobile
Project Name: esteem-mobile

Expected behaviour

The post should have been opened immediately or within 3 -4 secs
Actual behaviour
Here when I clicked on post it took longer time to open.
How to reproduce

1-Download the application
2- Go to the blog/post
3- Open it and notice the error

Browser/App version: v2.1.0
Operating system: 7.1.2
Smartphone: redmi 5A

Recording Of The Bug
https://youtu.be/g2Qt-FtmaGM

My Github Account

https://github.com/peerzadaaabid

**Comment by mistikk** [comment]
In this case, this post is very long, so it is expected behaviour. We changed render method with next release, it will more faster but long post takes more time than short posts @peerzadaaabid

**Comment by mistikk** [comment]
It is fixed, you can test with next release (v2.1.1)
