### ISSUE TITLE
[BUG] Got an error message when i tried to edit a post

### ISSUE THREAD

**Issue by cckole** [esteemapp/esteem-mobile#900]
**Describe the bug**
When I tried to edit my post, I got an error message

**To Reproduce**
1. Launch the app
2. Click on any of your post
3. Click on the edit icon
4. Edit 
5. Click okay and see error

**Expected behavior**

I expected that I should be able to edit my post successfully.

**Screenshots or Video**
https://youtu.be/WUrSFOy0SoE

**Smartphone (please complete the following information):**
 - Device: [Techno spark ]
 - OS: [Android 7.0]
 - Version [new version]

updated few hours ago today 6/6/2019

**Comment by ue** [comment]
fixed
