### ISSUE TITLE
[BUG] unable to redeem pending reward. Got an error message

### ISSUE THREAD

**Issue by cckole** [esteemapp/esteem-mobile#901]
**Describe the bug**
When I tried to redeem my pending reward, I got an error message and the reward wasn't redeemable

**To Reproduce**
1. Launch the app
2. Click on menu by the top left side and click profile
3. Click on wallet. If you have any pending reward, click on it to redeem.

**Expected behavior**
When I clicked on the pending reward yo redeem it, I expected it to be redeemed successfully.

**Screenshots or Video**
https://youtu.be/Eg4-vMOyiRw

**Smartphone (please complete the following information):**
 - Device: [Techno spark k7]
 - OS: [Android 7.0]
 - Version [ new version]

updated few hours ago today 6/6/2019

**Comment by mistikk** [comment]
@cckole it is fixed, can you check. If you still see this error, you can reopen to issue
