### ISSUE TITLE
Feature Request: Add new password for second account and show featured posts.

### ISSUE THREAD

**Issue by crysports** [esteemapp/esteem-mobile#917]
We have to enter the same password if we add another account to esteemapp which is something I don't like.
There should be separate password for separate accounts.
Featured posts are not displayed on the feed and I recommend that they should be shown on the feed.

**Comment by crysports** [comment]
I don't how how to remove this label but it is just a feature request, not a bug.

**Comment by ue** [comment]
what you mean about password. you wanted to say pin code or account password? @crysports

**Comment by crysports** [comment]
@ue
I meant pin code

**Comment by ue** [comment]
Feature post added, pin about app not related with account. so its not account spesific.
