### ISSUE TITLE
[BUG] esteem v2.1 The number of notifications are not omitted, even after viewing them.

### ISSUE THREAD

**Issue by peerzadaaabid** [esteemapp/esteem-mobile#919]
Project Information
Repository: https://github.com/esteemapp/esteem-mobile
Project Name: esteem-mobile

## Expected behaviour
The notification number should be omitted after viewing them, should new notification may pop up in notification icon.
## Actual behaviour
Here, the actual behaviour is exactly opposite to expected behaviour. The notification number remains as such, even after viewing them.
How to reproduce
1-Download the application
2- Go to the main page of feed
3- click on the notication icon
4- see bug

Browser/App version: v2.1.0
Operating system: 7.1.2
Smartphone: redmi note 4

Recording Of The Bug
https://youtu.be/P7F0mN1pBbY

My Github Account
https://github.com/peerzadaaabid

**Comment by ue** [comment]
If you press one of them the notificaiton can mark as view. other wise if you want to mark as read all ot them just press the check icon right of the header line. So work as designed.

**Comment by peerzadaaabid** [comment]
Plz have  look,
I'm taking about the red colour notification numbers as shown here in snap
https://drive.google.com/file/d/1E27WRLFSG9VE8mj6z4_sybIc56YhyhpX/view?usp=drivesdk
