### ISSUE TITLE
[BUG] esteem v2.1 the link in comment section ia not working

### ISSUE THREAD

**Issue by peerzadaaabid** [esteemapp/esteem-mobile#921]
Project Information
Repository: https://github.com/esteemapp/esteem-mobile
Project Name: esteem-mobile

Expected behaviour
The link should have been redirected the browser to its designed purpose.

Actual behaviour
Here, after clicking on the link, the link is not opened.
How to reproduce
1-Download the application
2- Go to the specific link in the comment section
3- click on the link
4- see bug

Browser/App version: v2.1.0
Operating system: 7.1.2
Smartphone: redmi note 4
# Recording
https://youtu.be/gALnIL7df_Q

My Github Account
https://github.com/peerzadaaabid

**Comment by ue** [comment]
Fixed please wait new release. thanx for report.
