### ISSUE TITLE
[BUG] eSteem v2.1 The text is not cleared,even after clearing it while posting.

### ISSUE THREAD

**Issue by peerzadaaabid** [esteemapp/esteem-mobile#952]
Project Information
Repository: https://github.com/esteemapp/esteem-mobile
Project Name: esteem-mobile

Expected behaviour
The text should have been cleared,after clicking on clear button.

Actual behaviour
Here,when I clicked on clear button ,the text is not cleared.
How to reproduce

1-Download the application
2- Enter some text and clear it.
3- Go to feed, and try to post again.
4- See error(the text you have already cleared, will be still there)

Browser/App version: v2.1.0
Operating system: 7.1.2
Smartphone: Note 4

Recording Of The Bug

https://youtu.be/t0mmCv6yXy4

My Github Account

https://github.com/peerzadaaabid

**Comment by ue** [comment]
Thank for your feedback.

Fixed. Wait for our new release 👍
