### ISSUE TITLE
Add support for tribes

### ISSUE THREAD

**Issue by shadutopian** [esteemapp/esteem-mobile#978]
A number of tribes are joining steemit since the inception of steem engine.
It will be nice if we see esteem support those tribes. 
By supporting I mean that we should be able to login and post through esteem.

**Comment by feruzm** [comment]
Hey @shadutopian, We will be launching communities feature soon. Which we think will be replacement of current steem engine tribes.

**Comment by shadutopian** [comment]
That will be nice.
Thank you
