### ISSUE TITLE
Ability to see the list of people who resteemed my posts

### ISSUE THREAD

**Issue by shadutopian** [esteemapp/esteem-mobile#986]
I am not a famous person on steemit, so it took me so long to come up with this suggestion. If we open a post, we see votes and comments but there are a few people who resteem our posts and it is really difficult to tell who resteemed your post if we don't have notifications enabled or visit the profile of that person.
Clearly, a famous person cannot check who resteemed his posts because sometimes there are too many. We do have an option on partiko to see how many people resteemed our posts but they are not clickable.
I want to suggest that esteem should take the lead and implement this feature where users will be able to see how many people resteemed their posts and clicking on that should show the list of those people. It will be an interesting feature to have on esteem.

**Comment by feruzm** [comment]
Thanks @shadutopian, we will consider this feature 👍

**Comment by ue** [comment]
Thanx for the feedback.
implemented @shadutopian
